### ISSUE TITLE
scala:cc loops continuously even if files don't change

### ISSUE THREAD

**Issue by matthughes** [davidB/scala-maven-plugin#102]
Using the latest 3.1.0 plugin with a link server running, 'mvn scala:cc' loops even when the files haven't changed.  This appears to be a change in behavior from 3.0.1.  

Looking through the source a bit, I thought all I had to do was change to use modified-only, but that is the old behavior that doesn't use zinc, if I read correctly.  I think the 'incremental' mode is supposed to be smart about what files changed, so maybe the bug is in there somewhere.  I'll try and look at it tonight and see if I can find out more.

**Comment by slandelle** [comment]
scala:cc should be dropped in favor of Bloop.

**Comment by slandelle** [comment]
Closing as I don't think this will ever be fixed.
IMHO, scala:cc is something that should be dropped in a future major version unless someone contribute a Bloop server support.
