### ISSUE TITLE
scala maven plugin 3.1.0 and intermittent crashes

### ISSUE THREAD

**Issue by jestan** [davidB/scala-maven-plugin#120]
I am using scala-maven-plugin  3.1.0  and getting following intermittent error in maven compile phase. I have to always run 'mvn clean' to proceed.

Maven compile phase output

https://gist.github.com/4661977#file-scala-maven-plugin-crash

Environment

Scala 2.10
Maven 3.0.3
Java version: 1.7.0 build 09
Ubuntu 12.04 64 bit 3.2.0-35-generic

**Comment by flovera1** [comment]
Hi
So, what's the solution to this problem?

**Comment by aswini-barik** [comment]
mvn clean or Run as Maven clean before Run as Maven install did help . This did resolve our Issue
