### ISSUE TITLE
wrong version of scala-compiler

### ISSUE THREAD

**Issue by mazurkin** [davidB/scala-maven-plugin#122]
I have a pure Java project (no Scala there) but I want to play with Scala console initialized with proper classpath.

After I've started the following command

<pre>
mvn org.scala-tools:maven-scala-plugin:2.15.2:console
</pre>

the error appeared

<pre>
[INFO] [scala:console {execution: default-cli}]
[WARNING] you don't define org.scala-lang:scala-library as a dependency of the project
[INFO] Checking for multiple versions of scala
Downloading: http://nexus.gainmatrix.com/nexus/content/groups/public/org/scala-lang/scala-compiler/0.0.0/scala-compiler-0.0.0.jar
[INFO] Unable to find resource 'org.scala-lang:scala-compiler:jar:0.0.0' in repository gainmatrix-repository-release (http://nexus.gainmatrix.com/nexus/content/groups/public)
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] wrap: org.apache.maven.artifact.resolver.ArtifactNotFoundException: Unable to download the artifact from any repository

Try downloading the file manually from the project website.

Then, install it using the command: 
    mvn install:install-file -DgroupId=org.scala-lang -DartifactId=scala-compiler -Dversion=0.0.0 -Dpackaging=jar -Dfile=/path/to/file

Alternatively, if you host your own repository you can deploy the file there: 
    mvn deploy:deploy-file -DgroupId=org.scala-lang -DartifactId=scala-compiler -Dversion=0.0.0 -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]

  org.scala-lang:scala-compiler:jar:0.0.0
</pre>

I could try to add some Scala dependencies to POM but I have to delete these before commit so that's not a good solution for me

**Comment by crifan** [comment]
Same reason here: not designate scala version

solution:

for `pom.xml`, add:

```xml
  <properties>
    <scala.version>2.13.5</scala.version>
```

in which `2.13.5` is scala latest version, installed on here MacOS by `brew install scala`
