### ISSUE TITLE
Maven version 3.0.4 required

### ISSUE THREAD

**Issue by bnord01** [davidB/scala-maven-plugin#130]
When trying to USE the scala-maven-plugin to build another project with Maven 3.0.3 I get:

[ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.1.4:compile (default) on project snn: The plugin net.alchim31.maven:scala-maven-plugin:3.1.4 requires Maven version 3.0.4 -> [Help 1]

While the description says only Maven 3.0+ is required.

While I have no problem updating to maven 3.0.4/5 myself, I think 3.0.4 is a rather harsh requirement to put on a shared project. I this absolutely necessary?

**Comment by luciferak** [comment]
Error resolving version for 'net.alchim31.maven:scala-maven-plugin': Plugin requires Maven version 3.0.4
Facing this error repeatedly when trying to run HiBench
