### ISSUE TITLE
fork argument: Scala NSC compiler terminates Maven

### ISSUE THREAD

**Issue by JAlexoid** [davidB/scala-maven-plugin#144]
Setting the compiler forking to false causes the compiler to terminate Maven's VM.
The issue lies with the fact that the compiler has a sys.exit() call as the last thing. Therefore it will inadvertently terminate the VM.

See here https://github.com/scala/scala/blob/master/src/compiler/scala/tools/nsc/Driver.scala#L69

Therefore any value for fork, other than true, is useless.

**Comment by slandelle** [comment]
Closing, I think this is no longer an issue.
Will reopen if someone chimes in.
