### ISSUE TITLE
Compile sources with scala 2.11

### ISSUE THREAD

**Issue by jcerdeira** [davidB/scala-maven-plugin#145]
Hi,

First let me know that you guys are doing a great job supporting the maven plugin for scala.

In my project we need to compile the sources with scala version 2.11 because we need to have case class with more than 22 parameter (I'm using a webservice that requires that).

Do you guys have an estimation to have the plugin working with scala 2.11 ?

Thanks in Advance,
João Cerdeira

**Comment by plalloni** [comment]
@davidB Works great with scala-maven-plugin 3.2.0! Thanks.
