### ISSUE TITLE
When using zinc server, classpath seems to get mixed up

### ISSUE THREAD

**Issue by martinburger** [davidB/scala-maven-plugin#147]
We use Jenkins to test our Scala projects. To decrease compilation time in order to get faster feedback, we would like to use zinc.

Unfortunately, it seems that using the zinc server mixes up the classpath. We get the following error when we switch on this feature:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.17:test (default-test) on project messaging: groups/excludedGroups require TestNG or JUnit48+ on project test classpath -> [Help 1]
```

I assume that using the zinc feature somehow ends up in having an older version of JUnit on the classpath.

Note: This could be related to #146.

**Comment by slandelle** [comment]
Zinc server support has been dropped, see #299.
Closing.
