### ISSUE TITLE
profile properties without activation interacts badly with intra-project POM dependencies

### ISSUE THREAD

**Issue by yziquel** [davidB/scala-maven-plugin#152]
Hi.

I noticed the following FAQ item for compiling for multiple scala versions.

https://github.com/davidB/scala-maven-plugin/wiki/frequently-asked-questions#cross-building-with-maven

I have a similar use case of profiles. However, I have two submodules A and B where B depends on A. Therefore transitive dependencies of B are pulled by scala-maven-plugin by looking at the POM of A. There are scala-specific properties to be interpolated in the POM of A, and these properties come from a profile P.

If the profile declaration of P contains an activation statement, maven properties are properly interpolated by the scala-maven-plugin. If the profile is activated manually with the mvn command line, these properties do not get interpolated in the POM of A, resulting in a failed build of B.

**Comment by smola** [comment]
I'm experiencing the same issue. Note that it could be a Maven problem: https://issues.apache.org/jira/browse/MNG-1388

**Comment by slandelle** [comment]
Purely maven question/issue. Moreover, maven version is not mentioned.
If someone is still interested, the best things to do would be to try to reproduce with latest maven version and with a pure java project.
Closing for now.
