### ISSUE TITLE
maven-scala-plugin should escape spaces when passing javac arguments in the *compile goal

### ISSUE THREAD

**Issue by Tcharl** [davidB/scala-maven-plugin#160]
Hi,

I noticed an enhancement to privide in the maven-scala-plugin:
In the compile and test-compile goals, m-s-p passes the scala-library jar location as an xbootclasspath argument to javac.

Unfortunately, while the scala-lib location contains spaces, these are not escaped, thus causing compilation problems (slashes replaced by dot in my CI environment).

Regards

**Comment by slandelle** [comment]
Closing for now: super old and I have no idea how to reproduce.
Will reopen if someone chimes in.

**Comment by Tcharl** [comment]
Hi @slandelle ,

You did well! it was a character encoding issue on my side. I didn't remember I filled this ticket

**Comment by slandelle** [comment]
Thanks a lot for your feedback. Honestly, I wasn’t expecting one after such a long time, that’s very kind of you:)
