### ISSUE TITLE
Usage doc still points to snapshot version

### ISSUE THREAD

**Issue by phatak-dev** [davidB/scala-maven-plugin#165]
Using the plugin [section](http://davidb.github.io/scala-maven-plugin/usage.html) of the doc, still mentiones the plugin version as **3.1.7-SNAPSHOT**. It takes extra effort to google and see that the plugin already is in stable *3.2.0* version. We need to update the wiki to reflect the latest stable version to help copy and paste use cases.

**Comment by davidB** [comment]
I upload the site with 3.2.0. no change on the wiki.

Thanks
