### ISSUE TITLE
Misplaced arguments when launching with scala:run

### ISSUE THREAD

**Issue by lefou** [davidB/scala-maven-plugin#169]
When launching an app with the `mvn scala:run` and the `-DmainClass` options, the started application gets the two invalid command line options `-deprecation` and `-feature`, which I think belong to the scala toolchain but not the user provided executable class.

Tested with 3.2.1

**Comment by davidB** [comment]
The plugin should not "inject" any args, including `-deprecation`. For any command run, compile,...
Do you define those args into your pom.xml somewhere ?

**Comment by lefou** [comment]
Yes, you are right. In one parent pom, there is such a configuration, but it is intended for use with the compiler, not the launcher. Sorry for the false alarm.

The issue is that the `args` options has different semantics in different goals. Should I open a new issue?

**Comment by davidB** [comment]
no new issue.
If args is defined in plugin's configuration (vs execution's configuration)
then it will be used for every command without configuration.
Tell me if you don't find a workaround. (I'll offline next ~24h).

**Comment by lefou** [comment]
There is no workaround when you use `scala:run` from the command line! IMHO, the run target should not re-use the `args` option which has the "add-to-the-call-of-the-favorite-scalac-tool" semantic.
