### ISSUE TITLE
make zinc host configurable

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [davidB/scala-maven-plugin#171]
currently, plugin uses zinc client constructor:
https://github.com/davidB/scala-maven-plugin/blob/master/src/main/java/sbt_inc/SbtIncrementalCompiler.java#L46

which can connect to zinc server via local host only: ("null" means "127.0.0.1") here:
https://github.com/typesafehub/zinc/blob/master/src/main/scala/com/typesafe/zinc/ZincClient.scala#L37

this complicates things needlessly for virtual networking (i.e. in docker), when plugin zinc client (say form jenkins docker instance) needs to talk to zinc server (running in another docker instance)

so, in given use case: 
- zinc client/sever instances, despite being run on the same physical host, 
- still are present on different networks and need be addressed as such

solution would be to expose one more plugin setting `zincHost`

**Comment by davidB** [comment]
fix in 3.4.2
