### ISSUE TITLE
Maven plugin should pass java.home to Zinc

### ISSUE THREAD

**Issue by dragos** [davidB/scala-maven-plugin#173]
When using the incremental compiler, `JAVA_HOME` has no effect until the zinc server is manually restarted. For example:
- compile with Java 8 on the PATH
- change JAVA_HOME to point to Java 7 (java -version confirms it's 1.7)
- rebuild with maven
- resulting Jar is still built against 1.8

**Comment by SashaOv** [comment]
+1 
hit this problem when trying to compile Spark to work on 1.7 JRE. Had to disable Zinc compiler altogether

**Comment by slandelle** [comment]
Zinc server support has been dropped, see #299.
Closing.
