### ISSUE TITLE
Package for Scala 2.7.11 to support Java 8?

### ISSUE THREAD

**Issue by bbarker** [davidB/scala-maven-plugin#176]
First, thanks for this wonderful plugin that allowed one of my projects to get up and running quickly with Scala support.

Another of my projects depends heavily on Java 8, and I will get the following error when I use e.g. Scala 2.7.2 as a dependency:

```
[ERROR] error: error while loading Consumer, class file 'C:\Program Files\Java\jdk1.8.0_25\jre\lib\rt.jar(java/util/function/Consumer.class)' is broken
```

Please let me know if I can help.

**Comment by davidB** [comment]
Scala 2.7.x is not compatible with java 8. You have to upgrade to scala 2.11.

**Comment by bbarker** [comment]
Apparently, I have some form of dyslexia with prime numbers... sorry!

**Comment by davidB** [comment]
np
