### ISSUE TITLE
Improved message for missing scala-library

### ISSUE THREAD

**Issue by janekdb** [davidB/scala-maven-plugin#182]
With no scala dependencies defined the warning message can be improved.

```
[WARNING] you don't define org.scala-lang:scala-library as a dependency of the project
Downloading: http://repo.maven.apache.org/maven2/org/scala-lang/scala-library/0.0.0/scala-library-0.0.0.jar
```

Better would be,

```
[ERROR] An org.scala-lang:scala-library dependency must be defined
```

Two changes,
1. Clearer message with clear call to action
2. ERROR not WARNING

Aborting with an error is more user friendly than forging on with a bogus version of the libraries.

I will be happy to issue a PR for this but equally happy if anyone else wants to grab it.

**Comment by davidB** [comment]
Your PR is welcome ;-)

**Comment by slandelle** [comment]
I took care of it.
