### ISSUE TITLE
The list of compiler plugin examples is empty.

### ISSUE THREAD

**Issue by janekdb** [davidB/scala-maven-plugin#183]
The list of compiler plugin examples is empty.

See: http://davidb.github.io/scala-maven-plugin/cc-mojo.html#compilerPlugins

Suggest to add miniboxing example adapted from SBT example here http://scala-miniboxing.org/using_sbt.html

**Comment by dwijnand** [comment]
Looks like a mistake in the Javadoc?

https://github.com/davidB/scala-maven-plugin/blob/3.3.1/src/main/java/scala_maven/ScalaMojoSupport.java#L147
