### ISSUE TITLE
cctest is not working

### ISSUE THREAD

**Issue by thirstycrow** [davidB/scala-maven-plugin#184]
Running cctest fails with the following error:

```
Local repository location: '${invoker.localRepositoryPath}}' is NOT a directory.
```

It seems to be the result of some misspelling here in [ScalaContinuousTestMojo.java#L39](https://github.com/davidB/scala-maven-plugin/blob/3.2.2/src/main/java/scala_maven/ScalaContinuousTestMojo.java#L39) in tag 3.2.1 and 3.2.2. The master branch is correct.

**Comment by davidB** [comment]
maybe fixed with version 3.3.3
