### ISSUE TITLE
Provide detail on how to use only the Scala compiler

### ISSUE THREAD

**Issue by Diagoras** [davidB/scala-maven-plugin#189]
It's possible to switch off Maven's Java compiler and use the Scala compiler for both Java and Scala source files by doing the following:

``` xml
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-compiler-plugin</artifactId>
    <executions>
        <execution>
             <id>default-compile</id>
             <phase>none</phase>
        </execution>
        <execution>
            <id>default-testCompile</id>
            <phase>none</phase>
        </execution>
    </executions>
</plugin>
<plugin>
    <groupId>net.alchim31.maven</groupId>
    <artifactId>scala-maven-plugin</artifactId>
    <executions>
        <execution>
            <id>compile</id>
            <phase>compile</phase>
            <goals>
                <goal>add-source</goal>
                <goal>compile</goal>
             </goals>
         </execution>
         <execution>
             <id>test-compile</id>
             <phase>test-compile</phase>
             <goals>
                 <goal>add-source</goal>
                 <goal>testCompile</goal>
              </goals>
         </execution>
     </executions>
</plugin>
```

Should information about this be placed in the Maven docs, the wiki, or both?

**Comment by davidB** [comment]
IIRC, the scala compiler doesn't compile java file.It can read them, but
not generate .class.
I guess a "mvn clean compile" will not generate .class from .java .

**Comment by Diagoras** [comment]
So, to be clear, the Java compiler is still run as part of your plugin. This just prevents Maven's default maven-compiler-plugin from executing so that you don't end up compiling the Java sources twice.

**Comment by lefou** [comment]
Correct.

There is one caveat though: If you enable to use zinc with the incremental mode (I don't exactly know which of both settings is the enabler), then scala-maven-plugin delegates to zinc to compile the sources, and zinc also compiles Java files. So, in case you have a mixed Java/Scala project, You can a) use the incremental mode and disable the java compiler from Maven or b) don't use the incremental mode and make sure the compile goal of this plugin runs before the compile goal of the java compiler plugin.

**Comment by slandelle** [comment]
Anybody up for a documentation contribution?

**Comment by slandelle** [comment]
Closing as stale.
