### ISSUE TITLE
Scaladoc is not generated for package object

### ISSUE THREAD

**Issue by skozlov** [davidB/scala-maven-plugin#193]
Steps to reproduce:
1. Clone https://github.com/skozlov/turing.git.
2. `mvn site`.

Scaladocs are generated successfully for the classes from modules `base` and `build`, but not for the package objects from `math`, `math00`, `math01`.

**Comment by slandelle** [comment]
Could you please upgrade to modern versions of this plugin and Scala and report again is issue still happens?

**Comment by slandelle** [comment]
Closing as stale.
