### ISSUE TITLE
how to add excludes

### ISSUE THREAD

**Issue by algorithmdog** [davidB/scala-maven-plugin#202]
Hello, every one.

I have a problem to add excludes to scala-maven-plugin. There are two scala files:Spark_1.6.1.scala and Spark_2.0.1.scala in src/main/scala/test.  I want to exclude Spark_1.6.1.scala when compilation, so I write a pom.xml with the following setups.  But it doesn't work. 

May I do something incorrectly? How to add excludes correctly ?

          <plugin>
				<groupId>net.alchim31.maven</groupId>
				<artifactId>scala-maven-plugin</artifactId>
				<version>3.2.0</version>
				<executions>
					<execution>
						<id>scala-compile-first</id>
						<phase>process-resources</phase>
						<goals>
							<goal>compile</goal>
						</goals>
					</execution>
					<execution>
						<id>scala-test-compile-first</id>
						<phase>process-test-resources</phase>
						<goals>
							<goal>testCompile</goal>
						</goals>
					</execution>
					<execution>
						<id>attach-scaladocs</id>
						<phase>verify</phase>
						<goals>
							<goal>doc-jar</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<scalaVersion>${scala.version}</scalaVersion>
					<recompileMode>incremental</recompileMode>
					<useZincServer>true</useZincServer>
					<args>
						<arg>-unchecked</arg>
						<arg>-deprecation</arg>
						<arg>-feature</arg>
					</args>
					<javacArgs>
						<javacArg>-source</javacArg>
						<javacArg>${java.version}</javacArg>
						<javacArg>-target</javacArg>
						<javacArg>${java.version}</javacArg>
					</javacArgs>
					<excludes>
						<exclude>test/Spark_1.6.1.scala</exclude> 
					</excludes>
				</configuration>
       </plugin>

**Comment by davidB** [comment]
Hi,

"test" is the name of your package ?
I'm not sure if "incremental" mode support excludes.

**Comment by algorithmdog** [comment]
@davidB 
Thanks for your response. "test" is the name of my package. I test the excludes so I give the name carelessly.

OK, I will try it again with removing "incremental"
