### ISSUE TITLE
zinc next gen (sbt/zinc) support

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [davidB/scala-maven-plugin#208]
https://github.com/sbt/zinc

**Comment by Diagoras** [comment]
Looks like they've just reached their 1.0 release.

**Comment by davidB** [comment]
Right, I give a quick look/try to zinc 1.0. I don't have the time and the motivation to learn how to integrate zinc 1.0 (zero documentation, only sample test in scala), and to do the change in the plugin.

Anyway PR are welcome.

PS: I don't use the incremental mode with the plugin.

**Comment by davidB** [comment]
see https://github.com/sbt/zinc/issues/402

**Comment by lefou** [comment]
IMHO this is a eligible request. I can understand that you ( @davidB ) won't do it, but I suggest to re-open this issue and attach a help-wanted label to it. That way, we could better track the demand and work to do.

**Comment by Andrei-Pozolotin** [comment]
resoled by https://github.com/davidB/scala-maven-plugin/issues/226

**Comment by lefou** [comment]
This issue is actually not resolved by #226, which is only a promotion for another maven plugin, which is neither a drop-in replacement nor has it any documentation how to migrate.

**Comment by slandelle** [comment]
Done, will be shipped in 4.0.0.
