### ISSUE TITLE
Compile goal downloads multiple versions of scala-library

### ISSUE THREAD

**Issue by jeffalexander** [davidB/scala-maven-plugin#209]
We are trying to use the scala-maven-plugin version 3.2.2 and have configured the scalaVersion to 2.11.8. We are using a proxy maven repo in an environment which does not allow direct access to maven central.

We're finding the scala-maven-plugin during the compile goal attempts to download multiple versions of the scala-library and fails because some are missing. 

One guess is there is a side effect of the [checkMultipleScalaVersions](https://github.com/davidB/scala-maven-plugin/blob/master/src/main/java/scala_maven_dependency/CheckScalaVersionVisitor.java) feature that will cause dependency resolution on versions that are ultimately not used in the project because maven would eventually resolve to one version (2.11.8).

An example where we don't control the version miss-match is spark-core_2.11 (2.1.0) -> chill_2.11 (0.8.0) -> scala-library (2.11.7) which would therefore mean you need both scala-library 2.11.7 and 2.11.8 in your maven repo. 

We have noticed that even when we set checkMultipleScalaVersions=false it still tries to resolve multiple versions.

Our current workaround is to load multiple previous versions of scala-library to our proxy maven repo.

Does this sound accurate? Any other recommendations?

**Comment by slandelle** [comment]
It's been a very long time, but if anyone is still interested in this, it would be great to provide a reproducer.

My best guess is that maven is expected to download the pom.xml of every artifact in the dependency tree. Maybe it's smart enough to apply dependencyManagement first and if version is enforced, won't try to download multiple versions. Moreover, I would expect only pom.xml to be downloaded, not jars.

If nobody can come up with a reproducer, I'm in favor of closing this.

**Comment by slandelle** [comment]
No answer, closing for now.
Feel free to chime in if you can provide more information.
