### ISSUE TITLE
Installing the plugin on eclipse

### ISSUE THREAD

**Issue by hemanthannavarapu** [davidB/scala-maven-plugin#212]
Hello

I am new to using maven and scala on Eclipse. I am not able to install the plugin directly from the marketplace or other software site as I have configured a proxy and it doesn't seem to work.

 So, I am trying to download the zip and then install the plugin from local. However, eclipse is throwing an error when I choose the extracted folder to install the software from. 

I know this is dumb but I need some help. can you please help me with installing the plugin?

Thank you.

**Comment by davidB** [comment]
see my answer to your stackoverflow question:
https://stackoverflow.com/questions/44268631/installing-scala-maven-plugin-on-eclipse-from-local/44278347#44278347

**Comment by lagerspetz** [comment]
Hi, I think it's worth noting that the downloads from http://scala-ide.org/ contain everything you need out of the box (Eclipse, all the scala and maven plugins, color theme). You just need to File -> Import -> existing maven project and browse to your scala maven project folder with Eclipse.

If you prefer to augment your existing Eclipse installation with the scala-ide plugins, then that stackoverflow is probably the best help.
