### ISSUE TITLE
Unable to add Java Sources in mix scala java project

### ISSUE THREAD

**Issue by mshafieluru** [davidB/scala-maven-plugin#213]
Hi
During debug..the call is going from scala to java and message is getting printed in console.
However, when i am trying to bundle this as a single job, the java sources are not getting added. 
During mvn:compile in IntellijIDEA, i get the  error: 

error: object java is not a member of package com.test
[ERROR] import com.test.java.HelloWorld

and
error: not found: type HelloWorld
[ERROR]     val helloWorld = new HelloWorld

JAVA Class
======

public class HelloWorld {

    public String greetFramework() {
        String msg = "Greetings from Java to Scala";
        System.out.println(msg);
        return  msg;
    }
}

Invocation in Scala
=============

val helloWorld = new HelloWorld
val msg:String = helloWorld.greetFramework()
println("Message from java..." + msg)

My Pom.xml
=======
```

<build>
        <plugins>
            <plugin>
                <groupId>net.alchim31.maven</groupId>
                <artifactId>scala-maven-plugin</artifactId>
                <version>3.2.2</version>
                <executions>
                    <execution>
                        <id>compile</id>
                        <goals>
                            <goal>compile</goal>
                        </goals>
                        <phase>compile</phase>
                    </execution>
                    <execution>
                        <id>test-compile</id>
                        <goals>
                            <goal>testCompile</goal>
                        </goals>
                        <phase>test-compile</phase>
                    </execution>
                    <execution>
                        <phase>process-resources</phase>
                        <goals>
                            <goal>compile</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <artifactId>maven-assembly-plugin</artifactId>
                <version>2.5.3</version>
                <configuration>
                    <descriptorRefs>
                        <descriptorRef>jar-with-dependencies</descriptorRef>
                    </descriptorRefs>
                    <archive>
                        <manifest>
                            <mainClass>com.test.scala.Main</mainClass>
                        </manifest>
                    </archive>
                </configuration>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>


```
Please help in resolving this 

regards
Shafi

**Comment by davidB** [comment]
1. stupid question: is class HelloWord part of the package "com.test" ?

2. As your scala code depends of java code, you can remove the compilation during phase "process-resources" keep it during "compile" phase.
(scala compilation should be done during one phase, not both).

3. Do you store .scala and .java under the same directory (my recommendation, easier to manage and to configure) or do you store them under .../scala and .../java in this case what is the value of your sourceDirectory ?

**Comment by mshafieluru** [comment]
Hi David.

Thanks for the clarifications. 

1. Yes the HelloWorld is part of the com.test.java package
2. Thanks. 
3. The folder structure is src/main/java , src/main/scala
4. The packaging is done for demo purpose only.

The java class is not being detected by scala.

Do i need to add maven compiler plugin on top of this plugin.
Can i set the source directory under <build> to /src as i cannot pass comma separated source directory

regards
Shafi

**Comment by hepin1989** [comment]
@mshafieluru Could you please provide a sample project :)

**Comment by mshafieluru** [comment]
Hi This is working
i will close this ticket

**Comment by davidB** [comment]
@hepin1989 you have samples under https://github.com/davidB/scala-maven-plugin/tree/master/src/it

**Comment by mshafieluru** [comment]
Thank you very much
