### ISSUE TITLE
Using incremental build with Zinc locks a file and prevents it from being deleted (Windows 10)

### ISSUE THREAD

**Issue by eyalroth** [davidB/scala-maven-plugin#216]
Using the plugin configured with an incremental build using Zinc server on Windows 10 causes a strange bug in which the Zinc process locks some of the output jars and prevents them from being deleted (and perhaps even modified).

Steps to reproduce:
 1. Download the following project: [zinc-bug.zip](https://github.com/davidB/scala-maven-plugin/files/1277464/zinc-bug.zip)
 2. Start a Zinc server.
 3. Run `maven install` from the root of the project.
 4. Run `maven clean` from the same location.

Make sure that when running `mvn install` you see the message `[INFO] Using zinc server for incremental compilation`.

On the last step you'll see that Maven cannot delete one of the files. Trying to delete it manually fails as well. Trying to unlock it with utility apps such as Process Explorer fails as well. Only a restart to the Zinc server releases the file.

I had originally created this issue in the new Zinc repository (sbt/zinc#404), but they have referred me here.

**Comment by davidB** [comment]
Hi,

Like pointed in the discussion on sbt/zinc#404, the zinc integration in the scala-maven-plugin is based on the typesafe zinc, and was done/contributed by a guy from typesafe. The fix includes to migrate to zinc 1.0, but see [davidB/scala-maven-plugin#208](https://github.com/davidB/scala-maven-plugin/issues/208). I don't have time and motivation to do it, but PR are welcome. The fix also require to have Windows 10 to test (I don't have it).

Thanks for reporting, and for creating the sample.

**Comment by dwijnand** [comment]
> the zinc integration in the scala-maven-plugin is based on the typesafe zinc, and was done/contributed by a guy from typesafe

Oh I hadn't realised that. See https://github.com/davidB/scala-maven-plugin/pull/95. Ping @pvlugter, perhaps he has motivation/interest in upgrading this to Zinc 1 (https://github.com/davidB/scala-maven-plugin/issues/208).

**Comment by pvlugter** [comment]
Sorry, I won't be working on this.
