### ISSUE TITLE
maven-scala-plugin:2.15.2:compile failed: For artifact {null:null:null:jar}: The groupId cannot be empty.

### ISSUE THREAD

**Issue by zhouhoo** [davidB/scala-maven-plugin#224]
When I build maven spark project , I encounter the build error:

Failed to execute goal org.scala-tools:maven-scala-plugin:2.15.2:compile (scala-compile-first) on project miui_ad_spark_ssp: Execution scala-compile-first of goal org.scala-tools:maven-scala-plugin:2.15.2:compile failed: For artifact {null:null:null:jar}: The groupId cannot be empty.

env:
ubuntu16.04,
jdk 1.8,
maven 3.5.2,
maven-scala-plugin:2.15.2
idea 2017.3.1

I tried clean, rebuild, google same question, but got almost nothing. 
Can anyone give me a hand?

**Comment by isomarcte** [comment]
@zhouhoo that appears to be using an old version of the plugin have you tried the most recent releases?

**Comment by davidB** [comment]
try with a recent version of the plugin.
