### ISSUE TITLE
thank you

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [davidB/scala-maven-plugin#226]
@davidB

David:

1) thank you for the plugin, it served us well
it seems it has reached the end of its useful life (?)

2) just to let you know, we produced  the next incarnation 
of scala plugin: https://github.com/random-maven/scalor-maven-plugin

3) in case you would like to participate in the "new life",
we sent you collaborator invitation to join the project, it will need support

Thank you,

Andrei.

**Comment by davidB** [comment]
@Andrei-Pozolotin,

Thanks for the invitation. I'll take a look, but no contributions (planned)t.

I let the issue open (with tags) to be visible, when you though confident enough, you can PR an update in the README and the doc to add link to scalor.

I wish you success

/davidB

**Comment by lefou** [comment]
As it looks, this project is not end-of-life. It works well and is also the reference scala maven toolchain, e.g. in Polyglot Maven or as a basis for Bloop. Also, it sees new releases. It looks to me, the only thing that will not magically happen is a port to zinc 1.x, unless someone provides it via PR.

As the note about scalor is already in the README, I'm for closing this issue.

**Comment by davidB** [comment]
I said to @Andrei-Pozolotin  that the project is +/- EOL, because I started the project 10+ years ago. And only do maintenance on it (minimal support). I do less & less scala, and I don't use maven at work.

**Comment by slandelle** [comment]
Zinc support has been upgraded to latest Zinc. Compile server has been dropped for now though, but might come back some day with Bloop.

Should this be closed?
