### ISSUE TITLE
Unable to generate java-10 bytecode (class-file version 54)

### ISSUE THREAD

**Issue by andreak** [davidB/scala-maven-plugin#275]
(Using Scala-2.12.6)
I have this configured in the plugin-config:
```xml
<args>
	<arg>-release</arg>
	<arg>10</arg>
</args>
```
But the class-file version is still 52 (java8)
Am I doing something wrong or isn't this supposed to work?

**Comment by davidB** [comment]
where do you see that scalac could generate java10 bytecode for *.class ?

**Comment by andreak** [comment]
I thought that that was what the "-release" compiler-option mentioned here: https://docs.scala-lang.org/overviews/compiler-options/index.html
did...
But I see it doesn't mention version 10. Are you saying that providing "9" instead of "10" _will_ generate java-9 bytecode (haven't tried)?

**Comment by andreak** [comment]
Hm, providing -release 9 using jdk10 gives this error:
```
[INFO] Compiling 1 Scala source to /home/andreak/dev/officenet_origo/macros/target/classes...
[INFO] Artima SuperSafe(TM) 1.1.6 activated (licensed to 104012, expires on 10 jun. 2019). Copyright (C) 2015 Artima, Inc. All Rights Reserved.
[ERROR] Class jdk.internal.HotSpotIntrinsicCandidate not found - continuing with a stub.
[ERROR] Class jdk.internal.HotSpotIntrinsicCandidate not found - continuing with a stub.
[ERROR] Class jdk.internal.HotSpotIntrinsicCandidate not found - continuing with a stub.
[ERROR] Class jdk.internal.HotSpotIntrinsicCandidate not found - continuing with a stub.
[ERROR] Class jdk.internal.HotSpotIntrinsicCandidate not found - continuing with a stub.
[ERROR] 5 errors found
```

**Comment by slandelle** [comment]
AFAIK, it's not possible, and anyway, that would be a question for the Scala compiler mailing list.
I'd vote for closing this.
