### ISSUE TITLE
scala version configuration

### ISSUE THREAD

**Issue by mycaule** [davidB/scala-maven-plugin#277]
```
$ mvn -version

Apache Maven 3.5.2 (Red Hat 3.5.2-5)
Maven home: /usr/share/maven
Java version: 1.8.0_172, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.172-9.b11.fc28.x86_64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.17.3-200.fc28.x86_64", arch: "amd64", family: "unix"
```

```xml
<!-- POM.xml -->
      <properties>
        ...
        <scala.version>2.11</scala.version>
      </properties>
      ...
      <plugin>
        <groupId>net.alchim31.maven</groupId>
        <artifactId>scala-maven-plugin</artifactId>
        <version>3.3.2</version>
	<configuration>
          <scalaVersion>2.11</scalaVersion>
        </configuration>
      </plugin>
```
Running `mvn scala:cc` I get this error

```
error: Implementation restriction: case classes cannot have more than 22 parameters.
```

but not with `mvn compile`

My project uses Scala 2.11 whereas my system scala (linux distribution) is Scala 2.10.

```
$ scala -version
Scala code runner version 2.10.6 -- Copyright 2002-2013, LAMP/EPFL
```

Scala 2.11 removed that 22 parameters restriction:
https://stackoverflow.com/questions/20258417/how-to-get-around-the-scala-case-class-limit-of-22-fields

In my `pom.xml` I explicitly specified the `scalaVersion` as told in:
http://davidb.github.io/scala-maven-plugin/usage.html

What am I missing ?

**Comment by davidB** [comment]
1. instead of configure scalaVersion in scala-maven-plugin, add the dependencies to the scala-library version, you want.
2. define the full exact scala version eg 2.11.11

So add

```xml
<dependency>
    <groupId>org.scala-lang</groupId>
    <artifactId>scala-library</artifactId>
    <version>2.11.11</version>
</dependency>
```

and remove the property (useless if only used once), remove the scalaVersion configuration (it's deduced from the dependency)

**Comment by mycaule** [comment]
Thank you, I tried it, but I still have the problem.

**Comment by davidB** [comment]
Can you share a minimal sample project with the issue ?

**Comment by mycaule** [comment]
Uninstalling scala on the operating system solved the problem.
