### ISSUE TITLE
scaladoc for submodule support

### ISSUE THREAD

**Issue by lanking520** [davidB/scala-maven-plugin#278]
Hi,

I am trying to use the `Scaladoc` plugin to generate javadoc jar on Maven. I have a big project contains several modules in Maven. However I see that plugin will generate the javadoc in each of the submodule but not wrapping it up together at one place. I created a assembly stage to combine all of the jar files to the same place but it seemed not working.

**Comment by lanking520** [comment]
#222

**Comment by slandelle** [comment]
Closing as duplicate of #222
