### ISSUE TITLE
scala-maven-plugin shouldn't require latest maven version

### ISSUE THREAD

**Issue by slandelle** [davidB/scala-maven-plugin#292]
Bonjour David,

With dependabot-bot, you've been upgrading dependency versions on a regular basis.

In eba83f60c0e883f51e384d6a9c350d98ddf840f8 and 93de71106287290e35fe4feb994309657a99d926, you've bumped maven version to 3.5.3 and then 3.5.4. The `maven.version` property is also used to fill the `<prerequisites>` block.

As a consequence, this plugin only works with most up-to-date maven version, and would refuse to launch otherwise.

Is this is really intended?

IMHO, requiring to only use very latest maven version is way too aggressive:
* official maven plugins require maven 3.0
* AFAIK, there's really nothing in this plugin that requires latest maven version
* Some environments ships older yet fine maven versions, eg Debian stable comes with maven 3.3.9.

Could you please revert?

**Comment by davidB** [comment]
You're right. I'll revert during the week-end.

**Comment by slandelle** [comment]
Awesome, thanks!

**Comment by davidB** [comment]
3.3.9 selected as maven version (for dependencies and for build)

**Comment by slandelle** [comment]
Thanks a lot! Any ETA for next release?

**Comment by davidB** [comment]
no ETA (I could not release from my current deskopt maven GPG issue on
macosx, and my linux (from where I released is currently K.O)

**Comment by slandelle** [comment]
crossing fingers...

**Comment by fantayeneh** [comment]
Hi David,  any chance this to be pushed to maven central
Thanks

**Comment by davidB** [comment]
@fantayeneh , I currently have several issue to resolve in the release pipeline, I hope to release during week-end.

**Comment by davidB** [comment]
@slandelle, @fantayeneh @andreak

scala-maven-plugin 3.4.4 is  available on maven-central, I changed the release process, feel free to open ticket for any trouble.

**Comment by andreak** [comment]
Works, thanks!

**Comment by slandelle** [comment]
Thanks a lot!
