### ISSUE TITLE
Test scope dependencies available during compile phase

### ISSUE THREAD

**Issue by daragallagher** [davidB/scala-maven-plugin#293]
I have a mixed Scala/Java project using the recommended pom.xml for this type of module.  I do not have a compile dependency on scala-reflect but it's a transitive dependency in the test scope via the scalatest dependency.

I noticed that I had been accidentally using scala-reflect classes from src/main/scala source.  The scala-maven-plugin does not complain and will happily compile the code.  However if I attempt to run a Scala main method using mvn exec:java -Dexec.mainClass=..., it blows up with java.lang.NoClassDefFoundError which is what you'd expect: the scala-reflect module is only available in the test scope according to mvn dependency:tree
 
If I reference the same class from source in src/main/java, then maven-compiler-plugin complains and refuses (correctly) to compile the Java source.

It looks like the scala-maven-plugin does not separate the test from the compile scope?

**Comment by slandelle** [comment]
Could you please share a simple maven project that reproduces the problem you describe?

**Comment by slandelle** [comment]
Couldn't reproduce with 4.2.4.
