### ISSUE TITLE
Can't seem to find 3.4.3 on maven-central

### ISSUE THREAD

**Issue by andreak** [davidB/scala-maven-plugin#295]
Something wrong with the release-process?

**Comment by slandelle** [comment]
https://github.com/davidB/scala-maven-plugin/issues/292#issuecomment-431890532

**Comment by davidB** [comment]
Right, got issue with release 2.4.3 will not be public.

Sorry.

**Comment by andreak** [comment]
Keep up the good work, appreciate it!
