### ISSUE TITLE
`maven.repo.local` path containing `+` character breaks build

### ISSUE THREAD

**Issue by m0** [davidB/scala-maven-plugin#304]
When a `maven.repo.local` path containing `+` character is specified, the build breaks with:

```[ERROR] Error: Could not find or load main class scala_maven_executions.MainWithArgsInFile```

This behaviour can be reproduced with latest version `3.4.4` 

## steps to reproduce
* create clean environment using docker
  ```docker run --rm -t -i maven:3.6.0-jdk-8-slim bash```
* inside container create scala maven project from archetype
  ```mkdir /src && cd /src && mvn archetype:generate -B -DarchetypeGroupId=net.alchim31.maven -DarchetypeArtifactId=scala-archetype-simple -DarchetypeVersion=1.7 -DgroupId=com.example -DartifactId=project -Dversion=0.1-SNAPSHOT -Dpackage=com.example```
* upgrade plugin-version
  ```sed -i 's/3.3.2/3.4.4/' /src/project/pom.xml```
* run maven with custom maven repo path containing ```+```
  ```cd /src/project && mvn -Dmaven.repo.local=/tmp/foo+bar clean verify```
this will make the build fail with
  ```[ERROR] Error: Could not find or load main class scala_maven_executions.MainWithArgsInFile```
* removing the ```+``` character from the path will result in a successful build

**Comment by slandelle** [comment]
Works fine with 4.2.4.
