### ISSUE TITLE
Broken testcompile when using Maven option -T 2C

### ISSUE THREAD

**Issue by FelixReuthlingerBMW** [davidB/scala-maven-plugin#306]
We are using the latest (3.4.4) version of the plugin within our Maven build, the build sometimes (not always) breaks during testcompile:

[ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.4.4:compile (default) on project xyz: wrap: org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]

with details:

[INFO] --- scala-maven-plugin:3.4.4:testCompile (scala-test-compile) @ xyz ---
...
[ERROR] pathtoclass.scala:23: error: not found: value SparkSession
[ERROR]     val spark = SparkSession.builder.getOrCreate
...
(as an example of multiple errors)

While the according import is for sure inside this class (sorry cannot attach full source).
Also other errors happen where some reference cannot be found.

We can see this issue happening sometimes, not predictable, also compile next run without changes on the same build. But as far as we can see this issue just happens when using Maven's option -T 2C for having 2 threads per core for the build. When decreasing to 1C the issues is completely gone.

Is there any experience with such issues?

Best regards
Felix

**Comment by davidB** [comment]
Sorry I never tried the plugin with multi-thread. 
TBH I don't think it's a good idea, because the plugin spawn a process to launch scalac (to support any version of scala). So having multiple thread that spawn the process could generate issue like what you have.

**Comment by FelixReuthlingerBMW** [comment]
Thank you a lot for the clarification, bit unfortunate to not use multithreading, but we guessed it might come from this root cause.
