### ISSUE TITLE
No cooperation between plugin 4.0.0 and scala 2.13

### ISSUE THREAD

**Issue by pzygielo** [davidB/scala-maven-plugin#326]
After upgrade of `scala-maven-plugin` from [3.4.6](https://github.com/davidB/scala-maven-plugin/releases/tag/3.4.6) to [4.0.0](https://github.com/davidB/scala-maven-plugin/releases/tag/4.0.0) following is reported by maven:
```
[ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:4.0.0:compile (scala-compile-first) on project scala-maven-plugin: Execution scala-compile-first of goal net.alchim31.maven:scala-maven-plugin:4.0.0:compile failed: For artifact {org.scala-sbt:compiler-bridge_2.13:null:jar}: The version cannot be empty. -> [Help 1]
```
See [travis](https://travis-ci.org/pzrep/scala-maven-plugin-4.0.0-2.13/builds/501424069) for example.

**Comment by slandelle** [comment]
4.0 switched default recompile mode from `all` to `incremental`. `incremental` is based on Zinc, which is not available yet for Scala 2.13 milestones.

Try switching back to `all`.

**Comment by pzygielo** [comment]
Overriding default for `recompileMode` helped indeed.
Thank you @slandelle.
:fireworks:

**Comment by slandelle** [comment]
Working on getting a cleaner exception with proper explanation.

**Comment by slandelle** [comment]
Thanks for your feedback.

**Comment by slandelle** [comment]
FWIW, I've tried forcing plugin dependency to `org.scala-sbt:zinc_2.12:1.3.0-M2` as there's a `org.scala-sbt:compiler-bridge_2.13.0-M5:1.3.0-M2`.

Sadly, `zinc_2.12:1.2.5` we compile against and `zinc_2.12:1.3.0-M2` are not compatible.

I'm afraid we won't be able to support `incremental` mode for Scala 2.13 milestones. We'll have to wait for a stable zinc release.

cc @davidB
