### ISSUE TITLE
Version inconsistancy mvn repo vs web

### ISSUE THREAD

**Issue by Zejnilovic** [davidB/scala-maven-plugin#329]
Maven repo is telling me the latest is 4.0.0 and your web is talking about 4.0.1. 

- 4.0.1 I am able to use
- 4.0.0 throws errors at me and I think they are not on my side

**Comment by davidB** [comment]
4.0.1 was published Thuesday, but maven repository could take time to mirror (generally 24H).
for my POV 4.0.1 and 4.0.0 are available:

- https://search.maven.org/search?q=g:net.alchim31.maven%20AND%20a:scala-maven-plugin&core=gav
- http://repo2.maven.org/maven2/net/alchim31/maven/scala-maven-plugin/4.0.0/
- http://repo2.maven.org/maven2/net/alchim31/maven/scala-maven-plugin/4.0.1/

**Comment by Zejnilovic** [comment]
Thanks for the prompt reply and URLs

I am updating multiple dependencies in the project and I have noticed that it is not actually this plugin's error that is the problem, but it is multiple known issues across the dependencies.

I am going to close this now.
