### ISSUE TITLE
Seperate folder for integration tests

### ISSUE THREAD

**Issue by vijaydaiict** [davidB/scala-maven-plugin#339]
I have project structure like this with it as integration tests.

src/main/resources
src/main/scala
src/test/recources
src/test/scala
src/it/scala
src/it/resources

Is there a way to make the plugin compile and places the resources and classes in the IT folder to the target testcalsses folder?? 

i have added the following configuration `<testSourceDir>src/it/scala</testSourceDir>` to make the it testes compile and copying the IT resources to regula test resources to make it work

**Comment by davidB** [comment]
I'm  not aware of a simple solution to compile `src/test/scala` and `src/it/scala` into the same destination.

From my understanding of your use case, it should be simpler to have all your tests under the same folder `src/test/scala` with:
- use a (top) package  'it', if you want to group them together
- use the "tag" feature of your test framework
- setup 2 executions goal in maven for the 2 phases

If you look at the `src/it` folder of this project you will not that it it's a group of small project. It should be the case for a plugin or a lib (for an app it is different), each it project integrate the root project like a user (else it is not a real integration test IMHO).

**Comment by timw** [comment]
You can add a second test-source folder using the `build-helper` plugin, which will then be compiled into testclasses
This mostly comes down to how you like to organise - all the test runners (surefure, scalatest) will find all tests in testclasses and you'll need some scheme (tagging, naming) to separate the executions.

```
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>build-helper-maven-plugin</artifactId>
				<executions>
					<execution>
						<id>add-test-source</id>
						<phase>generate-test-sources</phase>
						<goals>
							<goal>add-test-source</goal>
						</goals>
						<configuration>
							<sources>
								<source>src/test/cscala</source>
							</sources>
						</configuration>
					</execution>
				</executions>
			</plugin>
```

**Comment by slandelle** [comment]
Agree `build-helper-maven-plugin` is the way to go.
Closing.
