### ISSUE TITLE
displayCmd = true is ignored with default recompileMode

### ISSUE THREAD

**Issue by pzygielo** [davidB/scala-maven-plugin#354]
It took me a while to find out why setting
https://github.com/davidB/scala-maven-plugin/blob/3dd9f993c3f0dc1ee93df3617c8847c22c7c607d/src/main/java/scala_maven/ScalaMojoSupport.java#L270
to `true`, as described in https://github.com/davidB/scala-maven-plugin/blob/3dd9f993c3f0dc1ee93df3617c8847c22c7c607d/src/site/xdoc/usage.xml.vm#L43-L44
gives me no result.

I suppose, with that default (unchanged by me) https://github.com/davidB/scala-maven-plugin/blob/3dd9f993c3f0dc1ee93df3617c8847c22c7c607d/src/main/java/scala_maven/ScalaCompilerSupport.java#L40
`displayCmd` does not matter for https://github.com/davidB/scala-maven-plugin/blob/3dd9f993c3f0dc1ee93df3617c8847c22c7c607d/src/main/java/scala_maven/ScalaCompilerSupport.java#L96

If I'm right, which I'm not quite sure I am, perhaps doc could mention that `displayCmd` is for `RecompileMode.all` only, or something could be displayed in https://github.com/davidB/scala-maven-plugin/blob/3dd9f993c3f0dc1ee93df3617c8847c22c7c607d/src/main/java/sbt_inc/SbtIncrementalCompiler.java#L109
before dispatching to Zinc?

**Comment by davidB** [comment]
You're right, the doc should be updated. `displayCmd` is for when a process (cmd) is spawned, in  the incremental mode (the new default), no process is spawned.

**Comment by pzygielo** [comment]
Understood, thanks!
