### ISSUE TITLE
Missing Documentation Option "doc-external-doc"

### ISSUE THREAD

**Issue by pmwmedia** [davidB/scala-maven-plugin#360]
Is there any way to set a comma-separated list of classpath_entry_path#doc_URL pairs describing external dependencies via scala-maven-plugin?

I need to set external dependencies for scaladoc to get rid of all my warnings `Could not find any member to link for "xyz"`. The option "doc-external-doc" is explained on the [scaladoc man page](https://www.scala-lang.org/files/archive/nightly/docs-2.10.2/manual/html/scaladoc.html).

**Comment by davidB** [comment]
You can try using "args" for any scaladoc option:
```xml
<args>
  <arg>–doc-external-doc</arg>
  <arg>url1,url2</arg>
</args>
```
predefined configuration entry like `windowtitle` are sugar to avoid the arg syntax.

**Comment by pmwmedia** [comment]
It seems that scaladoc tries to read all arguments as a file. I cannot even set a document title using "args".

```xml
<args>
  <arg>–doc-title</arg>
  <arg>TEST_1</arg>
</args>
```

```
[INFO] --- scala-maven-plugin:4.0.1:doc-jar (doc-jar) @ tinylog-api-scala ---
error: IO error while decoding –doc-title with UTF-8: –doc-title (system cannot find the specified file)
Please try specifying another one using the -encoding option
error: IO error while decoding TEST_AB with UTF-8: TEST_1 (system cannot find the specified file)
Please try specifying another one using the -encoding option
```

**Comment by davidB** [comment]
Can you run with `-DdisplayCmd=true` then we could debug the command line launched.
As you can see in https://github.com/davidB/scala-maven-plugin/blob/master/src/it/test_goal_doc/pom.xml#L41 args is the way to pass argument (except doctitle) to scaladoc.

**Comment by pmwmedia** [comment]
Finally, I have succeeded to pass the arguments properly.

@davidB Thank your for your support!

**Comment by razajafri** [comment]
@pmwmedia how did you resolve your problem?

**Comment by pmwmedia** [comment]
@razajafri I have given up passing the doc title as argument. However, all arguments starting with a hypen `-` works (see davidB's example).
