### ISSUE TITLE
Incremental compiler API incompatibility with Scala Compiler 2.13.1

### ISSUE THREAD

**Issue by martin-g** [davidB/scala-maven-plugin#363]
Upgrading from 2.13.0 to 2.13.1 fails my build with:

```
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:4.2.0:compile (scala-compile-first) on project wicketstuff-scala: Execution scala-compile-first of goal net.alchim31.maven:scala-maven-plugin:4.2.0:compile failed: An API incompatibility was encountered while executing net.alchim31.maven:scala-maven-plugin:4.2.0:compile: java.lang.NoSuchMethodError: 'scala.tools.nsc.settings.AbsSettings$AbsSetting scala.tools.nsc.Settings.nowarn()'
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>net.alchim31.maven:scala-maven-plugin:4.2.0
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/home/martin/.m2/repository/net/alchim31/maven/scala-maven-plugin/4.2.0/scala-maven-plugin-4.2.0.jar
...
```

Related-to: https://github.com/scala/bug/issues/11742

**Comment by slandelle** [comment]
Thanks for reporting. Actually, the problem is similar, but here it's a zinc component that gets broken. I've opened an issue against zinc: https://github.com/sbt/zinc/issues/698

**Comment by dom-nguyen** [comment]
Is there any update on this please? Seeing that the discussion over sbt/zinc seems to indicate the "precompiled binary" for compiler-bridge cannot be used.

**Comment by slandelle** [comment]
Renaming issue to make it clear that only the `incremental` compiler mode suffers from this incompatibility issue and not the `all` one.

**Comment by slandelle** [comment]
@davidB Would you mind cutting a release, please?

**Comment by davidB** [comment]
@slandelle , I have issue with the release process (I will diseable some of doc generation, api,... - useless). I'll try to release this week.

**Comment by slandelle** [comment]
Cool, thanks!

**Comment by davidB** [comment]
4.2.4 published on maven central

**Comment by slandelle** [comment]
Thanks!
