### ISSUE TITLE
incremental compiles seems broke in 4.2.0

### ISSUE THREAD

**Issue by tgravescs** [davidB/scala-maven-plugin#364]
We upgraded Spark maven to use scala-maven-plugin 4.2.0 (https://issues.apache.org/jira/browse/SPARK-28759) and it seems that the incremental compiles now do not work.  If I changed back to 3.4.4 version it works.  Spark jira tracking this - https://issues.apache.org/jira/browse/SPARK-29329. 

Wondering if this is a known issue or perhaps we need to update something?

**Comment by slandelle** [comment]
Using [this sample project](https://github.com/gatling/gatling-maven-plugin-demo), incremental compilation works just fine for me:

```
$ mvn clean test-compile
[INFO] Scanning for projects...
[INFO]
[INFO] ----------------< io.gatling:gatling-maven-plugin-demo >----------------
[INFO] Building gatling-maven-plugin-demo 3.2.1
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ gatling-maven-plugin-demo ---
[INFO] Deleting /Users/slandelle/Documents/dev/projects/gatling-03-samples/gatling-maven-plugin-demo/target
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ gatling-maven-plugin-demo ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/slandelle/Documents/dev/projects/gatling-03-samples/gatling-maven-plugin-demo/src/main/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ gatling-maven-plugin-demo ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ gatling-maven-plugin-demo ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 3 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ gatling-maven-plugin-demo ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- scala-maven-plugin:4.2.0:testCompile (default) @ gatling-maven-plugin-demo ---
[INFO] Using incremental compilation using Mixed compile order
[INFO] Compiling 4 Scala sources to /Users/slandelle/Documents/dev/projects/gatling-03-samples/gatling-maven-plugin-demo/target/test-classes ...
[INFO] Done compiling.
[INFO] compile in 6.7 s
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  8.174 s
[INFO] Finished at: 2019-10-03T22:31:55+02:00
[INFO] ------------------------------------------------------------------------
$ mvn test-compile
[INFO] Scanning for projects...
[INFO]
[INFO] ----------------< io.gatling:gatling-maven-plugin-demo >----------------
[INFO] Building gatling-maven-plugin-demo 3.2.1
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ gatling-maven-plugin-demo ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/slandelle/Documents/dev/projects/gatling-03-samples/gatling-maven-plugin-demo/src/main/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ gatling-maven-plugin-demo ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ gatling-maven-plugin-demo ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 3 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ gatling-maven-plugin-demo ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- scala-maven-plugin:4.2.0:testCompile (default) @ gatling-maven-plugin-demo ---
[INFO] Using incremental compilation using Mixed compile order
[INFO] compile in 1.7 s
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.871 s
[INFO] Finished at: 2019-10-03T22:32:04+02:00
[INFO] ------------------------------------------------------------------------
```

**Comment by slandelle** [comment]
I suspect you are confusing incremental compilation and zinc server.

The former saves compilation information in a local cache file, so next time compilation happens, embedded zinc can figure out what needs to be recompiled and what doesn't.

The latter was indeed dropped in scala-maven-plugin 4 as there was no one around capable of upgrading it to zinc 1.0. Zinc server is to be replaced with bloop anyway, but that's another story.

**Comment by tgravescs** [comment]
hmm, perhaps, basically my case the second run of mvn (like you did above) actually showed the compiling scala again like:

[INFO] Compiling 4 Scala sources to /Users/slandelle/Documents/dev/projects/gatling-03-samples/gatling-maven-plugin-demo/target/test-classes ...
[INFO] Done compiling.

I guess if you are saying zinc is the one responsible for that, it makes sense, but how did that work in your example above then?

**Comment by slandelle** [comment]
I have no idea which maven command you type (you copy pasted one of my logs). It would be better if you could provide the full CLI commands and logs like it did.

scala-maven-plugin runs embedded zinc and stores analysis results in `/target/analysis` (one file per goal, only test-compile is enabled in my sample).

**Comment by tgravescs** [comment]
sorry, I'll get you more specifics from Spark side. Maybe I misunderstood what you said. I think you said the zinc server was dropped in scala-maven-plugin 4 and your example is using version 4 so I was wondering how it was able to skip the recompile the second invocation of mvn test-compile you ran? 

Spark runs zinc. We call a build script (build/mvn - https://github.com/apache/spark/blob/master/build/mvn) which starts a zinc server.

build/mvn -Phadoop-3.2 -Phive-thriftserver -Phive -Pyarn -Pkinesis-asl -Pkubernetes -Pmesos -Phadoop-cloud -Pspark-ganglia-lgpl package -DskipTests

The specific pom file:
https://github.com/apache/spark/blob/aedf090ab7635db88f02f2c8302b56c2ee517944/pom.xml#L2239

I'll try out your sample app and look into the spark side logs more to see if I can provide more useful info,

**Comment by slandelle** [comment]
You don't understand what zinc is.
zinc is an module of sbt. It's an internal: it's not documented and doesn't provide a public API.

If you try digging into the code with limited time (my case), you can find a way to use it embedded.

If you're an expert on sbt internals (Lightbend and ScalaCenter sbt core committers, people working at Twitter on Pants, people working at JetBrain on IntelliJ's Scala plugin, etc), you can write integrations with Zinc's compilation server mode.

Then, people at Scala Center are now working on [Bloop](https://github.com/scalacenter/bloop) that aims at providing a compile server for Scala (built on top of zinc) with a public API.

scala-maven-plugin 3 used to provide a support for the 2 modes: embedded and compile server.
Back then, zinc version was 0.13, which is now deprecated and no longer maintained. zinc server mode was originally contributed by someone from Lightbend, but no one ever showed up to help maintaining.

scala-maven-plugin 4 targets zinc 1. The code is completely different (remember: internal, hence no public API nor documentation).
I was able to figure out how to upgrade the embedded mode and contribute it, but not the remote server one.

Moreover, I don't understand how a remote compile server makes sense for maven. maven is more intended as a one shot process where you run `mvn compile` from the command line and you're done, on contrary to tools such as sbt and IDEs that are used in interactive mode and need to be able to recompile automatically in the background.

All in all, if you to upgrade your build to scala-maven-plugin 4, the [zinc server option](https://github.com/apache/spark/blob/aedf090ab7635db88f02f2c8302b56c2ee517944/pom.xml#L2273) no longer exists.
[Incremental mode](https://github.com/apache/spark/blob/aedf090ab7635db88f02f2c8302b56c2ee517944/pom.xml#L2272) with embedded zinc is now the default.

I've updated the [official sample](https://github.com/davidB/scala-maven-plugin/tree/master/samples/prj_multi_modules), if you give it a try, you'll see that classes don't get recompiled if you don't modify them and run `mvn compile` a second time.

Now, if you can come up with a minimal reproducer sample that would exhibit a bug, I'll gladly investigate.
But sorry, I don't have time to investigate Spark build chain.

**Comment by tgravescs** [comment]
thank you for the detailed explanation, that makes sense now that the zinc server option no longer exists.

**Comment by slandelle** [comment]
Then, I would expect a fresh zinc server to be slower than a fresh embedded zinc because of the wire overhead. In your case, I really think the speed difference comes from Zinc 1 doing more (or more accurate) work.

**Comment by jturcotte** [comment]
I'm facing the same or a similar issue where 4.2.0 recompiles all files **even if the sources didn't change**, while 3.4.6 behaves as expected and doesn't recompile anything.

I noticed that the invalidation of the build only happens when I run `mvn package` in between. Using [your sample project](https://github.com/gatling/gatling-maven-plugin-demo) I can reproduce it, but only if I first move all source files from `src/test` to `src/main` and use compile instead of test-compile so that maven-jar-plugin accesses the files.

If I run `mvn compile && mvn compile -X` I get:

```
[INFO] Using incremental compilation using Mixed compile order
[DEBUG] No changes
[INFO] compile in 1.5 s
```

But if I run `mvn package && mvn compile -X` I get:

```
[INFO] Using incremental compilation using Mixed compile order
[DEBUG] 
Initial source changes: 
	removed:Set()
	added: Set()
	modified: Set()
Invalidated products: Set(/Users/me/gatling-maven-plugin-demo/target/classes/Recorder$delayedInit$body.class, /Users/me/gatling-maven-plugin-demo/target/classes/Engine.class, /Users/me/gatling-maven-plugin-demo/target/classes/IDEPathHelper.class, /Users/me/gatling-maven-plugin-demo/target/classes/IDEPathHelper$.class, /Users/me/gatling-maven-plugin-demo/target/classes/Recorder.class, /Users/me/gatling-maven-plugin-demo/target/classes/Recorder$.class, /Users/me/gatling-maven-plugin-demo/target/classes/Engine$.class, /Users/me/gatling-maven-plugin-demo/target/classes/computerdatabase/BasicSimulation.class, /Users/me/gatling-maven-plugin-demo/target/classes/Engine$delayedInit$body.class)
External API changes: API Changes: Set()
Modified binary dependencies: Set()
Initial directly invalidated classes: Set()

Sources indirectly invalidated by:
	product: Set(/Users/me/gatling-maven-plugin-demo/src/main/scala/IDEPathHelper.scala, /Users/me/gatling-maven-plugin-demo/src/main/scala/Engine.scala, /Users/me/gatling-maven-plugin-demo/src/main/scala/computerdatabase/BasicSimulation.scala, /Users/me/gatling-maven-plugin-demo/src/main/scala/Recorder.scala)
	binary dep: Set()
	external source: Set()
[DEBUG] All sources are invalidated.
[DEBUG] Initial set of included nodes: 
[DEBUG] Recompiling all sources: number of invalidated sources > 50.0% of all sources
[INFO] Compiling 4 Scala sources to /Users/me/gatling-maven-plugin-demo/target/classes ...
...
[DEBUG] Scala compilation took 4.448985256 s
[INFO] Done compiling.
[INFO] compile in 6.2 s
```

The weird thing is that e.g. Engine.class has the same modified time after I run `mvn package`, so it's as if it was using the .class files access time to detect changes instead of the modification change. This is on macOS 10.14.6.

**Comment by slandelle** [comment]
@jturcotte Could you please confirm that issue happens only on JDK8 and not JDK9+?

**Comment by slandelle** [comment]
So... Issue only happens with Java 8 and is fixed with Java 9+.

Zinc compares lastModified timestamp to determine if it must prunes resources.
Prior to Java 9, Java's File.lastModified only had second resolution even though it's a timestamp.
In order to work around this issue, Zinc uses JNA and gets correct millis.

For some unknown reason, running `mvn package` truncates the lastModified timestamp of the generated class files and chop the millis.
I suspect some maven component is calling setLastModified with the original value.

**Comment by slandelle** [comment]
millis get lost on `mvn jar:jar` on Java 8...

**Comment by SethTisue** [comment]
nice detective work

**Comment by slandelle** [comment]
The culprit is plexus that does exactly what I was suspecting: read lastModified and set it back, losing millis in the process on Java 8.

**Comment by slandelle** [comment]
So actually, it looks like this issue has long been fixed.

By default, maven-jar-plugin version is 2.4.
Issue disappears if you force latest version:

```
<plugin>
    <artifactId>maven-jar-plugin</artifactId>
    <version>3.1.2</version>
</plugin>
```

I should have slept last night :(

**Comment by slandelle** [comment]
Speed issue is most likely a duplicate of #368
