### ISSUE TITLE
scala-maven-plugin version 4.2.4 throws error on Windows

### ISSUE THREAD

**Issue by tuhlmann** [davidB/scala-maven-plugin#370]
I created a sample project via `mvn archetype:generate` from `net.alchim31.maven:scala-archetype-simple`  version `1.7`. I only changed the version number of the scala-maven-plugin to `4.2.4`

Please find the sample project here: https://github.com/tuhlmann/scala-maven-plugin-error

After cloning the repo, simply issue a `mvn compile` to see the error.

The used jdk is Oracle Java 8.
The error thrown is 

```
[ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:4.2.4:compile (default) on project example: Execution default of goal net.alchim31.maven:scala-maven-plugin:4.2.4:compile failed: An API incompatibility was encountered while executing net.alchim31.maven:scala-maven-plugin:4.2.4:compile: java.lang.ExceptionInInitializerError: null
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>net.alchim31.maven:scala-maven-plugin:4.2.4
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/C:/Users/tuhlmann/.m2/repository/net/alchim31/maven/scala-maven-plugin/4.2.4/scala-maven-plugin-4.2.4.jar
...
[ERROR] urls[68] = file:/C:/Users/tuhlmann/.m2/repository/org/scala-lang/modules/scala-java8-compat_2.12/0.9.0/scala-java8-compat_2.12-0.9.0.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
```

For the full log please see https://github.com/tuhlmann/scala-maven-plugin-error/blob/master/README.md

As soon as I change the version to `4.2.0` or `3.3.2` it compiles fine.

Also, using `4.2.4` on Ubuntu 18.04 or macOS works fine, the problem only occurs on Windows, no matter if Oracke jdk or openJdk 8 is used.

Thanks for your help!

**Comment by slandelle** [comment]
Fixed, thanks for reporting!

**Comment by tuhlmann** [comment]
@slandelle Awesome, that was quick!

May I asked when this is planned to get released?

Thanks,
Torsten.

**Comment by slandelle** [comment]
ping @davidB ?

**Comment by slandelle** [comment]
@tuhlmann Could you please build from sources and validate the fix, I don't have a Windows box.

**Comment by tuhlmann** [comment]
@slandelle I built and installed `4.2.5-SNAPSHOT` locally and it does work on my sample project and also the real one that caused the problem.

Thanks!

I had to skipTests for install, otherwise there's this error surfacing:

```
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running scala_maven.LogProcessorUtilsTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.037 s - in scala_maven.LogProcessorUtilsTest
[INFO] Running scala_maven.MiscTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 s - in scala_maven.MiscTest
[INFO] Running scala_maven.VersionNumberTest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.003 s - in scala_maven.VersionNumberTest
[INFO] Running util.JavaLocatorTest
[ERROR] Tests run: 5, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.006 s <<< FAILURE! - in util.JavaLocatorTest  
[ERROR] shouldReturnNullWhenJavaIsNotAvailableOnCommandLineAndJavaHomeIsPresent(util.JavaLocatorTest)  Time elapsed: 0 s
  <<< FAILURE!
org.junit.ComparisonFailure: expected:<test[/bin/]java> but was:<test[\bin\]java>
        at util.JavaLocatorTest.shouldReturnNullWhenJavaIsNotAvailableOnCommandLineAndJavaHomeIsPresent(JavaLocatorTest.
java:19)

[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures: 
[ERROR]   JavaLocatorTest.shouldReturnNullWhenJavaIsNotAvailableOnCommandLineAndJavaHomeIsPresent:19 expected:<test[/bin
/]java> but was:<test[\bin\]java>
[INFO]
[ERROR] Tests run: 11, Failures: 1, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
```

**Comment by slandelle** [comment]
Thanks. I've pushed a commit to fix this test.

**Comment by tuhlmann** [comment]
@slandelle Thanks, `mvn install` works for me now.

**Comment by slandelle** [comment]
Cool, thanks for your feedback!

**Comment by anenviousguest** [comment]
@davidB could you please consider releasing this? That's a bummer to keep using a snaphost version published to the local repo😄

**Comment by davidB** [comment]
4.3.0 released, should be available in few hour on maven central's mirror.

Thank you guys

**Comment by tuhlmann** [comment]
@davidB Could you please check if the release went through? I still can't find it on https://mvnrepository.com/artifact/net.alchim31.maven/scala-maven-plugin

Thanks!

**Comment by slandelle** [comment]
@tuhlmann I can't stress this out enough: **people should stop using mvnrepository!**

mvnrepository's index always lags behind the official index which is https://search.maven.org.

Proof: https://search.maven.org/search?q=scala-maven-plugin
