### ISSUE TITLE
Can't use user property outputDir from the command line

### ISSUE THREAD

**Issue by jtconsol** [davidB/scala-maven-plugin#379]
Hi! I might be unterstanding something wrong, but the [documentation](https://davidb.github.io/scala-maven-plugin/compile-mojo.html#outputDir) states:

    <outputDir> | File | - | The directory in which to place compilation output
                             User property is: project.build.outputDirectory.

I should be able to overwrite a user-defined property, but I can't - running

    mvn scala:compile -Dproject.build.outputDirectory=test

...will still output to `target/classes`. I think this is because `project.build.outputDirectory` is part of Maven's POM model? In the [code](https://github.com/davidB/scala-maven-plugin/blob/master/src/main/java/scala_maven/ScalaCompileMojo.java#L24) it is defined as:

    @Parameter(property = "project.build.outputDirectory")
    private File outputDir;

It would be nice if the value from the POM model would be the default, but it could be overridden as a user property - Maybe it's possible like this?

    @Parameter(property = "outputDir", defaultValue = "${project.build.outputDirectory}")
    private File outputDir;

My use case is to compile all classfiles from the Scala sources, and only the Scala sources, which helps handling a rather large project I'm trying to contribute to.

**Comment by slandelle** [comment]
Agree. Willing to contribute a PR?

**Comment by jtconsol** [comment]
@slandelle: Sure, [here](https://github.com/davidB/scala-maven-plugin/pull/380) it is :)

**Comment by slandelle** [comment]
Thanks!
