### ISSUE TITLE
Feedback needed on plugin interfering with exclusions in reactor

### ISSUE THREAD

**Issue by fmarot** [davidB/scala-maven-plugin#382]
Hello,

this is not really a bug report but may become one: I recently inherited an 'old' scala module using  an old version of the plugin ( org.scala-tools:maven-scala-plugin:2.15.2 ).
I added the module into my Maven build reactor and it built fine.
Then I upgraded the plugin to the latest net.alchim31.maven:scala-maven-plugin:4.3.0 and it still built correctly. BUT it realized later that this changed seemed to have some unforeseen consequences on another module in my reactor.

This other module has a dependency on the module using the Scala Maven plugin, and it also uses the Maven Shade plugin. Normally the shaded jar is associated with a pom containing exclusions on some dependencies. But when using latest version of Maven scala plugin, those exclusions do not appear anymore in the resulting pom. If I switch back to the old version, exclusions appear again in dependency-reduced-pom.xml.

So my question is: is it expected in any way that the plugin might interfere with exclusions in the Maven dependency model ? Or did I simply not analyzed the problem correctly ?

I know that a SSCCE ( http://sscce.org/ ) would be welcome to make sure but I did not took the time yet, wanted to have you feedback first.

**Comment by slandelle** [comment]
Hello,

No, your problem doesn't ring a bell. Indeed, please provide a reproducer.

**Comment by fmarot** [comment]
I managed to reproduce the problem in a little multi-module sample: https://github.com/fmarot/test-scala-maven-plugin-issue-382
The README explains the 2 commands to launch to observe the behavior difference.

**Comment by slandelle** [comment]
Thanks.
Absolutely weird. Issue is not even related to all vs incremental recompileMode.

**Comment by slandelle** [comment]
Regression happened in 3.3.3. 3.3.2 is fine.

**Comment by slandelle** [comment]
The problem is with this commit: https://github.com/davidB/scala-maven-plugin/commit/b2ac53c723c3f90b2456d78bb918e413e1d92560

We can't remove it, as without it, we now get a NPE.
But it seems `dependencyTreeBuilder.buildDependencyGraph` messes up with the reactor.

**Comment by slandelle** [comment]
Fixed

ping @davidB

**Comment by fmarot** [comment]
You guys rock, you did it so fast ! Thanks :+1:

**Comment by davidB** [comment]
version 4.3.1 released on central https://repo1.maven.org/maven2/net/alchim31/maven/scala-maven-plugin/4.3.1/
