### ISSUE TITLE
scaladoc report under site:run

### ISSUE THREAD

**Issue by ekoepfle** [davidB/scala-maven-plugin#384]
Apologies in advance if this issue is already logged or fixed.  

I have been tracking down an issue with our scaladocs when using `mvn site site:run`, basically that external dependencies aren't found when generating the scaladoc.  On a generic site, clicking:  **reports** > **scaladocs** generates a class not found on **non-scala, non-project-src** imports.

I tracked it down to:

https://github.com/davidB/scala-maven-plugin/blob/master/src/main/java/scala_maven/ScalaDocMojo.java#L295
```scala
List<String> paths = new ArrayList<>(project.getCompileClasspathElements());   
```

During the `maven site:run runtime`, the project hasn't been "resolved", unlike the build phase.  If you drop a breakpoint there, during normal build phases, it returns all the jars.  However, during the `site:run` phases, the internal dependencies in `getArtifacts`  of the `MavenProject` remains empty.  Hence, the tempfile only contains the paths of the project's scala source code.

I am not sure how to force the resolve during the `site:run` cycle, if anyone knows that would be great!

I looked at the **project-info-reports** plugin, to see how they are generating dependency reports at runtime.  `ScalaMojoSupport` has all the pieces one needs to get to the list at site-run-time with their technique.  I was able to generate a useable scaladoc mainArgs temp file with changes below:

**ScalaMojoSupport.scala**
```scala
protected Set<Artifact> getCompileDependencies() throws Exception {
  ArtifactFilter filter = new ScopeArtifactFilter(Artifact.SCOPE_TEST);
  DependencyNode tree = dependencyTreeBuilder.buildDependencyGraph(project.getProjectBuildingRequest(), filter);
  Set<Artifact> dependencies = new HashSet<Artifact>();
  for (DependencyNode node : tree.getChildren()){
      dependencies.add(node.getArtifact());
  }
  return dependencies;
}
```

**ScalaDocMojo.java**
```
//java 6 syntax 
String outputDir = project.getBuild().getOutputDirectory();
List<String> paths = new LinkedList<String>();
for(Artifact a : getCompileDependencies()){
   if(a.getFile() != null){
      String p = a.getFile().getPath();
      if(!outputDir.equals(p)) {
         paths.add(p);
      }
   }
}
```

Hope this makes sense.  I can PR it too.  If you have any other tricks to fix, that would help too!

**Comment by davidB** [comment]
Thanks for the detailed issue, I didn't have time to investigate on my side yet. I'm not a maven expert, (I think I wrote this code part 5+ y ago based on a sample).

Yes PR are welcomed.

**Comment by ekoepfle** [comment]
No rush needed, I can look into it more and PR.  I am not certain what I pasted above is 100% stable either.  I ran a bunch of my employers projects through it and saw some noise.   The artifact list used to make the classpath in `MavenProject` is stateful, and I don't know the approved approach to populate it.

**Comment by slandelle** [comment]
It might not be populated because you directly run a mojo task instead of having it triggered from maven’s lifecycle.

**Comment by slandelle** [comment]
Closing as no answer from user.
Will reopen if we get more information, in particular an answer to my comment above.
