### ISSUE TITLE
Support for dotty compiler

### ISSUE THREAD

**Issue by danlehmann** [davidB/scala-maven-plugin#393]
As far as I can tell, the scala-maven-plugin doesn't support the dotty compiler (Scala 3.0) yet. This would be a useful feature to have to allow people to get their projects compatible early.

**Comment by slandelle** [comment]
Contributions welcome :)

**Comment by slandelle** [comment]
FWIW, I've upgraded zinc to 1.4.2, maybe this would help with Scala 3 support.

**Comment by andreacastello** [comment]
Hello. Using the last version (4.4.1) with a Scala 3.0.0-RC1 project it causes this error:
`Could not find artifact org.scala-lang:scala-library:jar:3.0.0-RC1`

I guess that this artifact name is built at runtime with a logic that is not valid for Scala 3 because the naming convention has changed (see: https://mvnrepository.com/artifact/org.scala-lang/scala3-library_3.0.0-RC1)

**Comment by aesteve** [comment]
Faced the same issue. Relevant snippet: https://github.com/davidB/scala-maven-plugin/blob/c35f69adaa7063fec9b4d884054ba9f6d5fff2fe/src/main/java/scala_maven/ScalaMojoSupport.java#L288

Is there a property or something we can override to test it any further? Thank you.

**Comment by slandelle** [comment]
Again: people, please be nice open source citizens: contribute!

If nobody contributes, I will definitely tackle it myself **someday**, meaning probably 1 year from now.

**Comment by andreacastello** [comment]
> Again: people, please be nice open source citizens: contribute!
> 
> If nobody contributes, I will definitely tackle it myself **someday**, meaning probably 1 year from now.

You are right. I'm sorry if my comment has been seen as a call to action: it wasn't. It was just a hint of where one of the "migration issues" may be. I have taken a look at the code: in the beginning I thought I could provide a quick fix for this, but now I think that making it work on dotty will require a much bigger effort than  just differentiating naming tokens for "scala" and "scala3". 

I'll try to experiment a bit (but, same as you, I have not much time to dedicate to it) and come back if I have something decent to share.

**Comment by aesteve** [comment]
Sorry of my comment sounded harsh or anything. I just had a look, saw the
constant in code and wanted to ask if there was a way to work around in
order to push experiments a bit further.
Sorry.

Le mer. 10 mars 2021 à 12:12, Andrea Castello <notifications@github.com> a
écrit :

**Comment by martin-g** [comment]
This issue could be closed in favour of this PR - https://github.com/davidB/scala-maven-plugin/pull/447

**Comment by davidB** [comment]
scala 3.0 support updated and release since 4.5.x
