### ISSUE TITLE
skipTests=true still building test sources

### ISSUE THREAD

**Issue by subprotocol** [davidB/scala-maven-plugin#396]
I ran into this when switching from com.google.code.sbt-compiler-maven-plugin to scala-maven-plugin.  I ran `mvn install -DskipTests=true` and noticed it was taking twice as long since moving over to scala-maven-plugin.

The unit tests do not run as I expect, but all the test sources still get compiled:
![image](https://user-images.githubusercontent.com/3710126/78838834-4102d400-79b4-11ea-8910-b85fb0c24c0e.png)

Using `-Dmaven.test.skip=true` does the proper behavior (skips compiling tests and running tests)

Would adding support for skipTests=true be a welcome contribution? It would put skipTests and maven.test.skip behaviors in sync. If so I would be happy to make this change.

It looks like it would just require small change to: https://github.com/davidB/scala-maven-plugin/blob/master/src/main/java/scala_maven/ScalaTestCompileMojo.java 

Thanks

**Comment by slandelle** [comment]
Please read: http://maven.apache.org/surefire/maven-surefire-plugin/examples/skipping-tests.html

> To skip running the tests for a particular project, set the skipTests property to true.
If you absolutely must, you can also use the maven.test.skip property to skip compiling the tests.

The current behavior is correct.

**Comment by subprotocol** [comment]
Ok, that makes sense.  thank you!
