### ISSUE TITLE
Cannot override recompileMode from POM.xml

### ISSUE THREAD

**Issue by bsolomon1124** [davidB/scala-maven-plugin#404]
Parent POM:

```
<recompileMode>incremental</recompileMode>
```

Command invocation:

```
mvn scala:compile -DdisplayCmd=true -DrecompileMode=all ...
```

In this setup, the output still shows:

```
 [INFO] Using incremental compilation using Mixed compile order
```

and does not display the command.

1. Is this the expected behavior?
2. Can I enforce `-DrecompileMode=all` and ignore the POM?

**Comment by slandelle** [comment]
AFAIK, this is not possible. You can't directly set/override maven plugin parameters from the command line.
The workaround is to use maven properties:

```
<configuration>
    <recompileMode>${recompileMode}</recompileMode>
</configuration>
```
