### ISSUE TITLE
can't just compile scala in src/main/scala without src/main/java

### ISSUE THREAD

**Issue by tldzyx** [davidB/scala-maven-plugin#407]
- src
  - main
    - java
      - JavaApp.java
      - KotlinInJavaApp.kt
      - ScalaInJavaApp.scala
    - kotlin
      - JavaInKotlinApp.java
      - KotlinApp.kt
      - ScalaInKotlinApp.scala
    - scala
      - JavaInScalaApp.java
      - KotlinInScalaApp.kt
      - ScalaApp.scala
    - resources

```
<build>
    <plugins>
        <!-- https://mvnrepository.com/artifact/org.jetbrains.kotlin/kotlin-maven-plugin -->
        <plugin>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-maven-plugin</artifactId>
            <version>${kotlin.version}</version>
            <executions>
                <execution>
                    <id>compile</id>
                    <phase>process-sources</phase>
                    <goals>
                        <goal>compile</goal>
                    </goals>
                    <configuration>
                        <sourceDirs>
                            <source>src/main/kotlin</source>
                        </sourceDirs>
                    </configuration>
                </execution>
                <execution>
                    <id>test-compile</id>
                    <phase>process-test-sources</phase>
                    <goals>
                        <goal>test-compile</goal>
                    </goals>
                    <configuration>
                        <sourceDirs>
                            <sourceDir>src/test/kotlin</sourceDir>
                        </sourceDirs>
                    </configuration>
                </execution>
            </executions>
        </plugin>
        <!-- https://mvnrepository.com/artifact/net.alchim31.maven/scala-maven-plugin -->
        <plugin>
            <!-- http://github.com/davidB/scala-maven-plugin -->
            <groupId>net.alchim31.maven</groupId>
            <artifactId>scala-maven-plugin</artifactId>
            <version>4.4.0</version>
            <executions>
                <execution>
                    <id>compile</id>
                    <phase>process-resources</phase>
                    <goals>
                        <goal>add-source</goal>
                        <goal>compile</goal>
                    </goals>
                    <configuration>
                        <sourceDir>src/main/scala</sourceDir>
                    </configuration>
                </execution>
                <execution>
                    <id>test-compile</id>
                    <phase>process-test-resources</phase>
                    <goals>
                        <goal>add-source</goal>
                        <goal>testCompile</goal>
                    </goals>
                    <configuration>
                        <testSourceDir>src/test/scala</testSourceDir>
                    </configuration>
                </execution>
            </executions>
        </plugin>
        <!-- https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-compiler-plugin -->
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-compiler-plugin</artifactId>
            <version>3.8.1</version>
        </plugin>
        <!-- https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-surefire-plugin -->
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-surefire-plugin</artifactId>
            <version>2.22.2</version>
        </plugin>
    </plugins>
</build>
```

After I compiled, in the `target\classes` dir, it's actual include
- JavaApp.class
- JavaInScalaApp.class
- KotlinApp.class
- KotlinApp$Companion.class
- ScalaApp.class
- ScalaApp$.class
- ScalaInJavaApp.class
- ScalaInJavaApp$.class

As expected, it's should be like this:
- JavaApp.class
- KotlinApp.class
- KotlinApp$Companion.class
- ScalaApp.class
- ScalaApp$.class

the `JavaInScalaApp` and `ScalaInJavaApp` should not be compiled because it's not in the `sourceDir`

What's the problem ? 
Am I config not correct or this is the plugin bug ?

**Comment by tldzyx** [comment]
## More Info:

### If comments the scala-plugin, the compiled result is this:
- JavaApp.class
- KotlinApp.class
- KotlinApp$Companion.class

### I tried `excludes` on plugin or execution, it's not work, nothing change

### I tried `includes` on plugin or execution, it's not correct, the scala file not compiled

**Comment by davidB** [comment]
If you want to add multiple sourcedir, try https://www.mojohaus.org/build-helper-maven-plugin/add-source-mojo.html, else compiler will not see other source folder so they will not be able to compile cross language language.

I don't understand why you split into 3 folders, if the 3 folders include .java, .kt and .scala

**Comment by tldzyx** [comment]
> I don't understand why you split into 3 folders, if the 3 folders include .java, .kt and .scala

It's a path rule, `/src/main/{language}/{packages}`, just like the standard path `/src/main/java/{packages}` use for java, it's let the same language in the same path

**Comment by slandelle** [comment]
First, I'm pretty sure the content of `src/main/java` gets compiled because you haven't [disabled](https://stackoverflow.com/questions/14614446/how-do-i-disable-the-maven-compiler-plugin) the `maven-compile-plugin`.

Secondly, your structure doesn't follow the maven standards. You're not supposed to mix different languages into the same sourceDirs, that's just a mess (and you won't find plugin maintainers willing to help your support this).
You should be using different sourceDirs.
And you shouldn't mix multiple apps into the same project root: use maven modules.
And if you want to be able to hand pick the technologies you want to enable, use maven profiles.

**Comment by davidB** [comment]
Supported (by java, kotlin, scala compiler plugin) layout are:
```
// 3x1
src/main
  java/**/*.java
  kotlin/**/*.kt
  scala/**/*.scala
```
Or 
```
// 1x3
src/main
  java/**
    *.java
    *.kt
    *.scala
```
But not the mix that you describe (with 3x3 aka 3 folder with 3 languages file)

**Comment by davidB** [comment]
To reply to your initial question, it's the expected behavior scala compiler should be able to see src/main/java and src/main/scala/**/*.java to be able to compile mixed project. In maven/gradle/sbt src/main is a whole, if you want to exclude, split then use module like @slandelle  said.
