### ISSUE TITLE
How can I use "mvn scala:doc" to make the latest version of scaladoc with new style? Why the scaladoc I make is with old style. 

### ISSUE THREAD

**Issue by Wang-Zhihui** [davidB/scala-maven-plugin#413]
How can I use "mvn scala:doc" to make the latest version of scaladoc with new style?
Like this: https://www.scala-lang.org/files/archive/api/current/index.html

Why the scaladoc I make is with old style.
Like this: https://www.scala-lang.org/api/2.10.3/#package

**Comment by slandelle** [comment]
You're getting it wrong: the scaladoc style depends on your Scala version.
What you see on https://www.scala-lang.org/files/archive/api/current/index.html is scaladoc style for latest stable version, ie Scala 2.13. You can't get this look and feel for older Scala versions.
