### ISSUE TITLE
Classpath order is not maintained

### ISSUE THREAD

**Issue by now** [davidB/scala-maven-plugin#431]
Previously, `getClasspathElements()` returned a `List`.  Now It returns a `Set` instead, which might seem reasonable, but the order of elements in the class path sometimes matters.  It should thus either be a `List` again or at least the implementation should use a `LinkedHashSet` instead of a `HashSet`.  Given that Maven itself deals with it as a `List` and the fact that `SbtIncrementalCompiler` wants a `List` in the end, returning this to a `List` is the best solution.

**Comment by slandelle** [comment]
Want to contribute a fix?

**Comment by davidB** [comment]
Since 4.5.0 the Set is a TreeSet so the order should be consistent when converted into a List (without impact from the order of insertion, ...).

Feel free to reopen, if you don't agree

**Comment by davidB** [comment]
I reopen, not all HashSet for classpath was removed.

**Comment by davidB** [comment]
done,  no more hashset for classpath, so the classpath(s) should be more stable.
