### ISSUE TITLE
Go-offline

### ISSUE THREAD

**Issue by Omri-sh** [davidB/scala-maven-plugin#433]
Hello,
I'm trying to download all the dependencies related to my scala project before build it. 
For that, I tried to use:
`mvn dependency:go-offline`
or go offline plugin:
`de.qaware.maven:go-offline-maven-plugin:resolve-dependencies`
But it seems that when I run `mvn install` the plugin still downloads dependencies.
Any suggestion on how I can achieve 'go-offline' capability?

**Comment by Omri-sh** [comment]
@davidB

**Comment by davidB** [comment]
Hi,

It's not a scala-maven-plugin question, but a general maven usage question or at least a question for the plugin you try to use.
Without any plugin, the maven workflow is to download and cache under `$HOME/.m2/repository` every dependency that are not already present. So if you don't have dependencies with special version number `*-SNAPSHOT` (or `LATEST`) every dependencies (from your project, and plugins) should be downloaded at the first call to "mvn install", then later call should just check the presence into your local cache.
You can enforce offline with the mvn flag `-o,--offline Work offline` (listed when you run `mvn --help`), could be usefull to ignore the SNAPSHOT check strategy (daily by default iirc).

**Comment by Omri-sh** [comment]
> Hi,
> 
> It's not a scala-maven-plugin question, but a general maven usage question or at least a question for the plugin you try to use.
> Without any plugin, the maven workflow is to download and cache under `$HOME/.m2/repository` every dependency that are not already present. So if you don't have dependencies with special version number `*-SNAPSHOT` (or `LATEST`) every dependencies (from your project, and plugins) should be downloaded at the first call to "mvn install", then later call should just check the presence into your local cache.
> You can enforce offline with the mvn flag `-o,--offline Work offline` (listed when you run `mvn --help`), could be usefull to ignore the SNAPSHOT check strategy (daily by default iirc).

Thank you for the answer @davidB,
I didn't mention it, but every build is done with docker multi-stage. So basically the local repo is always empty. That's why I use `go-offline`, to prevent downloading everything again on each build and take advantage of docker's stage.
When I run the command `go-offline` and then `mvn -o install` I get errors related to this plugin which states that some other dependencies are required and cannot be fetched in offline mode. Some of the dependencies are already existing ones in my project but with different version and some of them aren't part of my project. Any suggestion on how to handle that?

**Comment by slandelle** [comment]
First, as you don't take advantage of the incremental compiler, you should disable it (compile mode `all`) so you don't need zinc and the compiler bridge sources jar that need to fetched dynamically and compiled against your Scala version.

Then, add the remaining missing dependencies explicitly in your pom.xml so that they get downloaded in your dry run.
