### ISSUE TITLE
The document of scala-maven-plugin site is out-of-date

### ISSUE THREAD

**Issue by Yikun** [davidB/scala-maven-plugin#444]
Looks like the the doc of [scala-maven-plugin site](https://davidb.github.io/scala-maven-plugin/example_incremental.html) is out-of-date, such as the change [1] is missing.

Would you mind to publish the latest doc in the site?

[1] https://github.com/davidB/scala-maven-plugin/pull/408
[2] https://davidb.github.io/scala-maven-plugin/example_incremental.html

**Comment by davidB** [comment]
The site is updated when we released a new version, and no new version was release since the doc update. I'll do a patch release in a couple of days.

**Comment by Yikun** [comment]
@davidB Great, thanks for the info.

And looks like incremental feature (which is enabled by zinc 1.x) has been enable by default after 4.0.0, it would be good if we could do some rework on the "Incremental Compile" doc.

I will try to add a PR before release to make the incremental doc more clearly.

[1] https://davidb.github.io/scala-maven-plugin/example_incremental.html

**Comment by davidB** [comment]
Thanks, I'll wait your PR.

**Comment by Yikun** [comment]
Thanks for you wait, and would you mind take a look at https://github.com/davidB/scala-maven-plugin/pull/445? @davidB 

And also maybe cc https://github.com/davidB/scala-maven-plugin/pull/408 related guys.

cc @brandonbyskov @slandelle

**Comment by brandonbyskov** [comment]
The changes I made with #408 removed the outdated information I was aware of. There may be more outdated information on that page related to Zinc usage.

**Comment by davidB** [comment]
I released 4.4.1 with the update in the doc and some dependencies.

Thanks

**Comment by Yikun** [comment]
@davidB Great, thanks for your work.
