### ISSUE TITLE
mvn scala:compile works but mvn compile doesnt

### ISSUE THREAD

**Issue by xhudik** [davidB/scala-maven-plugin#448]
Hi there,

If I run:
`mvn scala:compile scala:run` all is working fine, but if I run:
`mvn compile` or `mvn package` - it finish successfully but I get nothing (no result classes)

Any idea why? I'd guess I'm missing some "glue" between `scala-maven-plugin` and `mvn`. I have tried to read your documentation, but didnt find anything 

Sorry - this is a question, not a bug/issue

**Comment by SethTisue** [comment]
> this is a question, not a bug/issue

@davidB perhaps enable the Discussions feature in this repo...?

**Comment by davidB** [comment]
I enable discussion, but IMHO every questions are issues (about the doc,...) that a user have with the tool.

Now to respond to the original request. can you share the fragment of your pom.xml where you declare usage of the scala-maven-plugin ?

it should look like

```xml
      <plugin>
        <groupId>net.alchim31.maven</groupId>
        <artifactId>scala-maven-plugin</artifactId>
        <version>4.4.1</version>
        <executions>
          <execution>
            <goals>
              <goal>compile</goal>
              <goal>testCompile</goal>
            </goals>
          </execution>
        </executions>
        ...
```

**Comment by xhudik** [comment]
hi, I just figured it out. My problem was that I included in inside  `<pluginManagement></pluginManagement>` I didnt know pom requires to define a plugin inside `pluginManagement` and then once more outside of this management. 

Maybe, some well-documented example pom file would help (me and other guys who are not well-versed in maven). I can give try and prepare some, if you think it make sense...

Other than this, I found `scala-maven-plugin` well documented (concise, easy to understand)

**Comment by davidB** [comment]
every contribution are welcomes.

**Comment by jozic** [comment]
@xhudik 
Yes please, send your PR if you think it will help someone else

**Comment by xhudik** [comment]
@jozic  - yep, i'll try to create something in a few weeks (im pretty busy next 14 days :()
