### ISSUE TITLE
Plugin increases build time

### ISSUE THREAD

**Issue by aravindraja007** [davidB/scala-maven-plugin#476]
I am using scala-maven-plugin version 3.3.2. When I try to execute a script using the plugin, it somehow tries to update one dependency _'org.bouncycastle:bcpkix-jdk15on'_. I am using a local artifactory repository to manage my dependencies.

```
23:39:37,746 [DEBUG] Determining update check for artifact org.bouncycastle:bcpkix-jdk15on (/Users/akannan7/.m2/repository/org/bouncycastle/bcpkix-jdk15on/maven-metadata-uhc.xml) from uhc (https://repo1.uhc.com/artifactory/maven-repo)
23:39:37,747 [DEBUG] Searching for uhc.maven-metadata-uhc.xml.lastUpdated in resolution tracking file.
23:39:37,748 [DEBUG] Reading resolution-state from: /Users/akannan7/.m2/repository/org/bouncycastle/bcpkix-jdk15on/resolver-status.properties
23:39:37,750 [DEBUG] Determining update check for artifact org.bouncycastle:bcpkix-jdk15on (/Users/akannan7/.m2/repository/org/bouncycastle/bcpkix-jdk15on/maven-metadata-central.xml) from central (https://repo.maven.apache.org/maven2)
23:39:37,752 [DEBUG] Searching for central.maven-metadata-central.xml.lastUpdated in resolution tracking file.
23:39:37,753 [DEBUG] Reading resolution-state from: /Users/akannan7/.m2/repository/org/bouncycastle/bcpkix-jdk15on/resolver-status.properties 
```

When I remove the plugin from project, it builds within 4 mins. If I add it back, this process runs in a loop and increases the build time of the project considerably by 12 mins. Please provide thoughts or suggestions to reduce the build time.

**Comment by davidB** [comment]
Can you try with a recent version of the plugin, like 4.5.2 ? (3.3.2 is 3yo version, and do some improvements and bug fix since)

**Comment by davidB** [comment]
@aravindraja007 
Can you try with a recent version of the plugin, like 4.5.2 ? (3.3.2 is 3yo version, and we did lot of improvements and bug fix since)

Without more info, I'll close the ticket.

**Comment by slandelle** [comment]
Closing as stale.
