### ISSUE TITLE
dotty.tools.xsbt.PositionBridge@3eec221b: could not find Lazy implicit value error when trying to upgrade the scala version to 3.0.0 

### ISSUE THREAD

**Issue by rajcspsg** [davidB/scala-maven-plugin#477]
Hi,

I'm sample maven scala project [here](https://github.com/rajcspsg/scala3-maven-build-demo)
When compiling the project with scala-maven-version 4.5.1 I get the below error.

>[ERROR] dotty.tools.xsbt.PositionBridge@767bb276: could not find Lazy implicit value of type scodec.Codec[adserver.cluster.serializer.TagRequest].
I found:
>
>    shapeless.Lazy.mkLazy[I]
>
>But method mkLazy in object Lazy does not match type shapeless.Lazy[scodec.Codec[adserver.cluster.serializer.TagRequest]].
>
>One of the following imports might make progress towards fixing the problem:
>
>  import shapeless.~?>.idKeyWitness
>  import shapeless.~?>.idValueWitness
>  import shapeless.~?>.witness

I added the below code from the error suggestion above.

```
import shapeless.~?>.idKeyWitness
import shapeless.~?>.idValueWitness
import shapeless.~?>.witness
```

After adding that I got below error.

>[ERROR] dotty.tools.xsbt.PositionBridge@39640f7b: could not find Lazy implicit value of type scodec.Codec[adserver.cluster.serializer.Event].
>I found:
>
>    shapeless.~?>.witness[Nothing, Nothing, T](shapeless.~?>.rel[Nothing, Nothing])

What is the error. How can I fix this for scala 3?

**Comment by davidB** [comment]
Sorry I didn't play enough with scala3 / dotty to help you.
Maybe try to contact the shapeless or scala3 community for help. And please reopen the ticket with more info if it is a issue with the plugin (In this case providing a minimal sample project case to reproduce the issue will help a lot).

Thanks

**Comment by mims-github** [comment]
@davidB 
May I "miss"-use this issue to check, if the following is  a problem in this plugin or a (configuration?) problem for the Scala3 compiler?

When a compile error is logged by the plugin, one has no way to find out, in which source file the problem actually is. Which makes fixing it quite hard. :sweat_smile: 
I guess that the `dotty.tools.xsbt.PositionBridge@767bb276: ` part in the log line should show the location of the problem, but it looks like the Object.toString is used instead a helpful custom toString impl.
https://github.com/lampepfl/dotty/blob/master/sbt-bridge/src/dotty/tools/xsbt/PositionBridge.java

Can you confirm?
Let me know how I can help.

Thanks a lot for the plugin!

**Comment by davidB** [comment]
@mims-github , yes using another issue was maybe a better place. Anyways any suggestions to improve the dev experience and help to resolve this issue directly or indirectly is welcomed (IMHO).

In this case, I also though that the improvement is on dotty or sbt-bridge side, if I'm wrong PR are welcomes, TBH I didn't did a lot in this issue (expected try to reproduce and check some configuration), and I'm no longer a scala user or dev (since several years now), so not the best to fix or to help on this (double) issue

**Comment by mims-github** [comment]
@davidB Thanks a lot for your quick feedback, very appreciated.
I will check with upstream projects, if we can improve from their side.

**Comment by mims-github** [comment]
FYI: Starting with nightly version 3.0.2-RC1-bin-20210611-fcd837a-NIGHTLY, a more informative source location info is logged for compile errors and warnings.
