### ISSUE TITLE
4.5.1 considers 2.13.2 and 2.13.5 different versions

### ISSUE THREAD

**Issue by jozic** [davidB/scala-maven-plugin#480]
Creating the issue per discussion https://github.com/davidB/scala-maven-plugin/discussions/468

I've just tried new version (4.5.1) of the plugin on a tiny project and got unexpected error

[INFO] --- scala-maven-plugin:4.5.1:compile (scala-compile-first) @ jsoniter-codecs_2.13 ---
[WARNING]  Expected all dependencies to require Scala version: 2.13.2
[WARNING]  com.ebay.ads:jsoniter-codecs_2.13:0.2.0-SNAPSHOT requires scala version: 2.13.2
[WARNING]  com.github.plokhotnyuk.jsoniter-scala:jsoniter-scala-macros_2.13:2.7.0 requires scala version: 2.13.5
[ERROR] Multiple versions of scala libraries detected!
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------

I have `<failOnMultipleScalaVersions>true</failOnMultipleScalaVersions>` but 2.13.2 and 2.13.5 should be compatible and scala-maven-plugin 4.4.1 was ok with that either

**Comment by rdefreitas** [comment]
I saw the same thing with 2.12.12 and 2.12.13 after upgrading to the 4.5.3 release from 4.3.0 

```
[WARNING]  Expected all dependencies to require Scala version: 2.12.13
[WARNING]  net.liftweb:lift-json_2.12:3.4.3 requires scala version: 2.12.12
[ERROR] Multiple versions of scala libraries detected!
```

I've had to temporarily disable failures on my build

**Comment by rondefreitas** [comment]
@davidB just a heads-up, seeing the same issue on 4.5.6

**Comment by slandelle** [comment]
@rondefreitas @jozic This one is probably a low hanging fruit. Contributions are very welcome!

**Comment by jozic** [comment]
looked into that and it seems that it's fine with different compatible versions of `scala-library` and `scala-reflect`, but it complains about a lib which depends on a different version of `scala-compiler`. AFAIU `scala-compiler` artifacts are not guaranteed to be compatible between bugfix/minor versions. So I guess the plugin is doing the right thing, maybe just with not very precise message

**Comment by slandelle** [comment]
I haven't checked the issue exactly, but indeed, compiler backward compatibility is not guaranteed across `minor` versions (Scala versioning scheme is `<epoch>.<major>.<minor>`). That's the reason why compiler plugins are now published against the `minor` version and not the `major` one.

**Comment by slandelle** [comment]
Stale. Closing for now.
Please provide a reproducer so we can investigate.
