### ISSUE TITLE
Scala.js Support

### ISSUE THREAD

**Issue by AugustNagro** [davidB/scala-maven-plugin#486]
Hi, does this plugin support Scala.js, or would it be interested in adding support?

**Comment by davidB** [comment]
I not aware of support of scala.js. PR are always welcomed.
Do you plan to use this plugin for Scala.js ?

**Comment by AugustNagro** [comment]
Yes I would be interested.

But since the effort to reimplement something like sbt-crossproject [1] is
high, I'm thinking it would be best to implement a
'sbt-delegate-maven-plugin', that simply downloads, caches, and runs sbt.

[1]: https://github.com/portable-scala/sbt-crossproject

**Comment by davidB** [comment]
Yes, in this case, starting a other maven plugin could be a better solution.
When you'll have a maven plugin, feel free to submit a PR for the README.md (or doc page) to add a link to it.
