### ISSUE TITLE
Publish for Scala 3

### ISSUE THREAD

**Issue by AugustNagro** [davidB/scala-maven-plugin#487]
For Scala 3 some of the dependencies have changed.

**Comment by martin-g** [comment]
The issue is not very clear but I think the reporter meant this error:

```
INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project presentation: Could not resolve dependencies for project com.mgsolutions:presentation:war:4.0-SNAPSHOT: The following artifacts could not be resolved: org.scala-lang:scala3-library_3.0.1-RC1:jar:3.0.1-RC1, org.scala-lang:scala3-compiler_3.0.1-RC1:jar:3.0.1-RC1: Could not find artifact org.scala-lang:scala3-library_3.0.1-RC1:jar:3.0.1-RC1 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
[ERROR] 
```


scala-maven-plugin resolves `scala3-library_3.0.1-RC1` while the published artefact is `scala3-library_3`. See https://search.maven.org/artifact/org.scala-lang/scala3-library_3/3.0.1-RC1/jar

CC @adpi2 and @rajcspsg

**Comment by martin-g** [comment]
Actually the problem was in my pom.xml which I created by following https://github.com/davidB/scala-maven-plugin/blob/master/src/it/test_scala3/pom.xml

```
<dependency>
      <groupId>org.scala-lang</groupId>
      <artifactId>scala3-library_${scala3.version}</artifactId>
      <version>${scala3.version}</version>
    </dependency>
    <dependency>
      <groupId>org.scala-lang</groupId>
      <artifactId>scala3-compiler_${scala3.version}</artifactId>
      <version>${scala3.version}</version>
    </dependency>
```

Here the artifactId should use just `3`, not `${scala3.version}`.

**Comment by davidB** [comment]
Thanks for the info.

Previously to scala 3 we used 2 properties.  Why not continue (if you mixed scala2 & scala3, in this case create your own properties x2) ?

```xml
    <dependency>
      <groupId>org.scala-lang</groupId>
      <artifactId>scala3-library_${scala.compat.version}</artifactId>
      <version>${scala.version}</version>
    </dependency>
    <dependency>
      <groupId>org.scala-lang</groupId>
      <artifactId>scala3-compiler_${scala.compat.version}</artifactId>
      <version>${scala.version}</version>
    </dependency>
  ```

**Comment by martin-g** [comment]
Sounds good!

**Comment by davidB** [comment]
I released a new version of the plugin. With simplest configuration required for scala 3 see the example https://github.com/davidB/scala-maven-plugin/blob/master/src/it/test_scala3/pom.xml.
