### ISSUE TITLE
Provide option to use FSC in scala:compile goal

### ISSUE THREAD

**Issue by GrahamLea** [davidB/scala-maven-plugin#49]
For multi-module Scala projects that have multiple compile phases, it would be great to be able to use FSC to speed up the compilation.

Even better would be if the FSC server could be started if one is not running.

**Comment by slandelle** [comment]
Closing as FSC support will most likely never happen. The current thing for this would be [Bloop](https://github.com/scalacenter/bloop) (contributions welcome).
