### ISSUE TITLE
The testCompile goal does not support the outputDir configuration option

### ISSUE THREAD

**Issue by lukehutch** [davidB/scala-maven-plugin#492]
The `testCompile` goal does not support the `outputDir` configuration option (but the `compile` goal does). Can you please add this option for `testCompile` too? Thank you.

**Comment by slandelle** [comment]
Contributions welcome!

**Comment by slandelle** [comment]
I'm not sure what the problem is here. It's just that the parameter is named `testOutputDir` for `testCompile`, not `outputDir`.

cc @davidB  @Dufgui

**Comment by lukehutch** [comment]
Thanks, maybe this can be closed then... I haven't worked on this for a long time now.

**Comment by slandelle** [comment]
@Dufgui WDYT? Does #638 really make senses?

**Comment by Dufgui** [comment]
I am fine to cancel it. It just a contribution to help. If it’s not follow the need just delete /cancel it :)

**Comment by slandelle** [comment]
@Dufgui Ok, will cancel then. Still, thanks for contributing, much appreciated!
