### ISSUE TITLE
When using scala 3.0.0, on compilation failure line number or file name not printed to console.

### ISSUE THREAD

**Issue by phoenix2082** [davidB/scala-maven-plugin#495]
If you $  % mvn scala:compile

and some of the Scala file has compilation error then line number and filename are missing from console log.
```
ERROR] dotty.tools.xsbt.PositionBridge@38b54694: Incompatible combinations of tabs and spaces in indentation prefixes.
Previous indent : 1 tab, 8 spaces
Latest indent   : 2 tabs
[ERROR] dotty.tools.xsbt.PositionBridge@7c6fc278: Not found: type Store
[ERROR] dotty.tools.xsbt.PositionBridge@5afd2f4e: value + is not a member of Option[String], but could be made available as an extension method.
```

**Comment by davidB** [comment]
Thanks, it seems to be an issue with dotty itself (not the scala-maven-plugin, see https://github.com/davidB/scala-maven-plugin/issues/477#issuecomment-851996374).

Hope that coming version will fix it.

**Comment by mims-github** [comment]
If you use Scala 3.1.0, it should be improved/fixed.

**Comment by slandelle** [comment]
Closing as this issue is not here.
