### ISSUE TITLE
toolchains support

### ISSUE THREAD

**Issue by nikita-sheremet-clearscale** [davidB/scala-maven-plugin#514]
Could you please add maven toolchains support to be able to build spark/scala multi module projects with different jdk versions?

For now toolchain pluing is not activated during scala compilation

https://maven.apache.org/guides/mini/guide-using-toolchains.html

**Comment by slandelle** [comment]
AFAIK, toolchain is supported: https://github.com/davidB/scala-maven-plugin/search?q=Toolchain

If you experience an issue, please contribute.
