### ISSUE TITLE
Class incorrectly reloaded in scala:console with :replay

### ISSUE THREAD

**Issue by janvandervorst** [davidB/scala-maven-plugin#53]
It seems that classes are incorrectly reloaded in the maven scala
console when issuing a :replay command.

// file: Foo.scala
class Foo { def m = 1 }
// end file

scala> val f = new Foo
..
scala> f.m
res0: Int = 1

then change Foo.scala to
// file: Foo.scala
class Foo { def m = 2 }
// end file

compile, and issue a replay in the same scala console
scala> :replay
..
scala>f.m
res0: Int = 1  // Should be 2

When adding new methods they are correctly added in the reloaded class
from which I conclude that the new class is actually reloaded.

I do not see the same problem in the bare scala REPL and neither in
the sbt console.

I see this behaviour both on Windows32 and Linux64.

**Comment by slandelle** [comment]
Closing as I don't think this will ever be investigate. IMHO, `scala:console` should be dropped in a future major version.
