### ISSUE TITLE
release 4.5.6 

### ISSUE THREAD

**Issue by asethia** [davidB/scala-maven-plugin#539]
sorry to open a new issue, because answer was not given and it is closed - https://github.com/davidB/scala-maven-plugin/issues/538 

scala maven plugin is dependent on zinc (org.scala-sbt). The dependency goes like this

org.scala-sbt:zinc_2.12:jar:1.3.5 -> org.scala-sbt:zinc-core_2.12:jar:1.3.5 -> org.scala-sbt:zinc-apiinfo_2.12:jar:1.3.5 -> org.scala-sbt:zinc-classfile_2.12:jar:1.3.5 -> org.scala-sbt:util-logging_2.12:jar:1.3.0 -> org.apache.logging.log4j:log4j-core:jar:2.11.2

I don't see 4.5.6 at https://mvnrepository.com/artifact/net.alchim31.maven/scala-maven-plugin

**Comment by slandelle** [comment]
1. Read again my previous answer: lib is not loaded
2. wait for the index to be updated. You can already download.
