### ISSUE TITLE
java.lang.NoSuchMethodError: scala.tools.nsc.Global.reporter()Lscala/tools/nsc/reporters/Reporter

### ISSUE THREAD

**Issue by Yikf** [davidB/scala-maven-plugin#553]
Thanks for this plugin, but i have a issue compiling with the following environment:

- scala version: 2.12.15
- scala-maven-plugin: 4.3.0

**errorMsg:**
[ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:4.3.0:compile (scala-compile-first) on project oap: Execution scala-compile-first of goal net.alchim31.maven:scala-maven-plugin:4.3.0:compile failed: An API incompatibility was encountered while executing net.alchim31.maven:scala-maven-plugin:4.3.0:compile: java.lang.NoSuchMethodError: scala.tools.nsc.Global.reporter()Lscala/tools/nsc/reporters/Reporter;
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>net.alchim31.maven:scala-maven-plugin:4.3.0
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/Users/yikaifei/.m2/repository/net/alchim31/maven/scala-maven-plugin/4.3.0/scala-maven-plugin-4.3.0.jar
[ERROR] urls[1] = file:/Users/yikaifei/.m2/repository/org/apache/maven/maven-builder-support/3.3.9/maven-builder-support-3.3.9.jar
[ERROR] urls[2] = file:/Users/yikaifei/.m2/repository/com/google/guava/guava/18.0/guava-18.0.jar
[ERROR] urls[3] = file:/Users/yikaifei/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.21/plexus-interpolation-1.21.jar
[ERROR] urls[4] = file:/Users/yikaifei/.m2/repository/javax/enterprise/cdi-api/1.0/cdi-api-1.0.jar
[ERROR] urls[5] = file:/Users/yikaifei/.m2/repository/javax/annotation/jsr250-api/1.0/jsr250-api-1.0.jar
[ERROR] urls[6] = file:/Users/yikaifei/.m2/repository/org/eclipse/sisu/org.eclipse.sisu.inject/0.3.2/org.eclipse.sisu.inject-0.3.2.jar
[ERROR] urls[7] = file:/Users/yikaifei/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.6/plexus-component-annotations-1.6.jar
[ERROR] urls[8] = file:/Users/yikaifei/.m2/repository/org/apache/maven/reporting/maven-reporting-api/3.0/maven-reporting-api-3.0.jar
[ERROR] urls[9] = file:/Users/yikaifei/.m2/repository/org/eclipse/aether/aether-util/1.0.2.v20150114/aether-util-1.0.2.v20150114.jar
[ERROR] urls[10] = file:/Users/yikaifei/.m2/repository/com/google/inject/guice/4.0/guice-4.0-no_aop.jar
[ERROR] urls[11] = file:/Users/yikaifei/.m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar
[ERROR] urls[12] = file:/Users/yikaifei/.m2/repository/org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.jar
[ERROR] urls[13] = file:/Users/yikaifei/.m2/repository/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar

**Comment by seriously6** [comment]
Any one have solutions for this issue?

**Comment by slandelle** [comment]
Please:
* upgrade to the latest version of this plugin
* if you still experience an issue, provide a sample project to reproduce

**Comment by seriously6** [comment]
> Please:
> 
> * upgrade to the latest version of this plugin
> * if you still experience an issue, provide a sample project to reproduce

Thanks for your reply

**Comment by seriously6** [comment]
> Please:
> 
> * upgrade to the latest version of this plugin
> * if you still experience an issue, provide a sample project to reproduce

what might this issue related to? because compile successfully in other project use same version(scala & plugin), i am wonder that is not related to the version. maybe it is my bad since the project

**Comment by slandelle** [comment]
> what might this issue related to?

No idea, that's why I'm asking for you to provide a simple reproducer.

**Comment by slandelle** [comment]
Closing as stale for too long.
Please chime in if you can provide a reproducer against the latest version of plugin.
