### ISSUE TITLE
scalac 2.11 do not understand -release option

### ISSUE THREAD

**Issue by gzm55** [davidB/scala-maven-plugin#585]
when compile with scala 2.11 and JDK 11, the java compiler understands -release option, but the scalac does not.

**Comment by slandelle** [comment]
The release option was introduced in scala 2.13.

**Comment by gzm55** [comment]
@slandelle 
On Scala 2.11 + JDK11 environment, the property `${maven.compiler.release}` is required by maven-compiler-plugin, but it will break the scala-maven-plugin.
