### ISSUE TITLE
JavaLocator return wrong path in JDK8

### ISSUE THREAD

**Issue by ysn2233** [davidB/scala-maven-plugin#627]
## Description
When I tried to build a project using scala-maven-plugin(4.7.0), it encountered an error: wrap: java.io.IOException: Cannot run program "/usr/lib/jvm/java-8-openjdk/jre/bin/javac".

## Cause
in class util.JavaLocater:
``` java
if (javaHomeSystemProperty != null) {
      if (javaHomeSystemProperty.endsWith(File.separator + "jre")) {
        // Old JDK versions contain a JRE. We might be pointing to that.
        // We want to try to use the JDK instead as we need javac in order to compile mixed Java-Scala projects.
        File javaExecFile = new File(javaHomeSystemProperty + File.separator + ".." + File.separator + "bin", javaCommand);
        if (javaExecFile.isFile()) {
          // getCanonicalPath to get rid of ".."
          return javaExecFile.getCanonicalPath();
        }
      }
```
javaExecFile path is `$JAVA_HOME/jre/../bin/java`, when use `javaExecFile.getCanonicalPath()`, it is expected to get `$JAVA_HOME/bin/java`.
However In openjdk8, $JAVA_HOME/bin/java is a soft link symbol to `$JAVA_HOME/jre/bin/java`, so `javaExecFile.getCanonicalPath()` returns `$JAVA_HOME/jre/bin`, which will cause the plugin cannot find javac executable when compile code. 

## Solution
Using absolutely path of JDK binary directory instead of using ".."  and canonical path.

**Comment by slandelle** [comment]
Fix in 4.7.1
