### ISSUE TITLE
deprecation warnings

### ISSUE THREAD

**Issue by rladstaetter** [davidB/scala-maven-plugin#646]
After updating to Scala 2.13.9 (and Java19 if that is relevant) I get various warnings like this:

`[WARNING] : -target is deprecated: Use -release instead to compile against the correct platform API.`

Any idea whats going on?

**Comment by slandelle** [comment]
https://www.scala-lang.org/news/2.13.9

https://github.com/davidB/scala-maven-plugin/commit/36453a1b6b00e90c5e0877568a086c97f799ba12
https://github.com/davidB/scala-maven-plugin/commit/627772b0c968693f6226b72c2e0ea7172ec795a1

sigh

**Comment by slandelle** [comment]
see #648

**Comment by slandelle** [comment]
fixed in 4.7.2

**Comment by rladstaetter** [comment]
MINDBLOWING! thank you very much. 💯

**Comment by rladstaetter** [comment]
just tried it out, works perfectly.
