### ISSUE TITLE
Yet another (maybe user-error) problem with 4.8.1

### ISSUE THREAD

**Issue by clayreimann** [davidB/scala-maven-plugin#691]
Hi I also tried to upgrade to version 4.8.1 and am running into compile errors. I've seen #683 and #686 and couldn't exactly follow their problems, but I did come up with a tiny build that exhibits the issue I've got in our larger build https://github.com/clayreimann/scala-maven-plugin-reproducer

Maybe I've just misconfigured something and you can point me in the direct of a fix. 

Unrelated to the compile error I also tried to set `<displayCmd>true</displayCmd>` and it doesn't seem to actually print anything. 

Also, thanks for taking the time to maintain this super useful maven plugin!

**Comment by slandelle** [comment]
Hi,

[These JVM args](https://github.com/clayreimann/scala-maven-plugin-reproducer/blob/main/pom.xml#L77-L80) are invalid and cause the forked JVM to crash.

First, `-Djava.net.preferIPv4Stack=true` is a System property, not a JVM option. I don't even know what you're trying to achieve with this and how it could be related to compiling code.

Then, you must pass options individually, not as a single string that contains spaces:

```xml
                    <jvmArgs>
                        <jvmArg>--add-exports</jvmArg>
                        <jvmArg>java.base/jdk.internal.misc=ALL-UNNAMED</jvmArg>
                        <jvmArg>--add-exports</jvmArg>
                        <jvmArg>java.base/jdk.internal.ref=ALL-UNNAMED</jvmArg>
                    </jvmArgs>
```
