### ISSUE TITLE
Why have this as 'unlicensed' when scala is apache 2 and this once was?

### ISSUE THREAD

**Issue by hazendaz** [davidB/scala-maven-plugin#708]
We can no longer procure these into our firm because of the license here.  I see this was apache 2 back in 2012 then moved to unlicensed.  I don't see the real motivation or why it would need to differ from scala.  Guessing due to more restrictive license scala once was.  But since 2018 its been apache 2.  Wondering if this project can be flipped back to apache 2?

**Comment by slandelle** [comment]
Only the owner @davidB can answer this question.

Then, why can't your firm allow a library that's explicitly [released in the public domain](https://github.com/davidB/scala-maven-plugin/blob/master/UNLICENSE)?

**Comment by davidB** [comment]
The license changed to become "public domain" (IIRC, at this time, CC-0 didn't exist, and SQLite also chose UNLICENSE).
It is not planned to change the license (it requires agreement from every contributor), and if any change it will stay in "public domain".

https://choosealicense.com/licenses/unlicense/
