### ISSUE TITLE
Maven Plugin Validation error? Depends on deprecated compatibility layer

### ISSUE THREAD

**Issue by hildo** [davidB/scala-maven-plugin#709]
Hi.  When I run a build that uses this plugin with a newer version of maven (3.9.2), I get a validation warning at the end.  When I run with maven.plugin.validation set to VERBOSE, I get this message: Plugin depends on the deprecated Maven 2.x compatibility layer, which may not be supported in Maven 4.x

![image](https://github.com/davidB/scala-maven-plugin/assets/1204224/2901dee2-25ae-4f62-a528-13272505d129)

If I have raised a duplicate, I apologize.  A search didn't reveal anything.

**Comment by slandelle** [comment]
Maven 3.9.2 was way too aggressive with these warnings. They fixed this in maven 3.9.3, please upgrade.

**Comment by hildo** [comment]
Can do!  Thanks
