### ISSUE TITLE
Exiting mvn scala:console leaves terminal unusable

### ISSUE THREAD

**Issue by tnm** [davidB/scala-maven-plugin#71]
Starting a console session in Terminal.app on OS X 10.6.6.

```
tnm$ echo $TERM
xterm-color

tnm$ mvn scala:console

Welcome to Scala version 2.9.1.final (Java HotSpot(TM) 64-Bit Server VM, Java 1.6.0_22).   
Type in expressions to have them evaluated.  
Type :help for more information.

scala> 
```

Exit with Control-C or Control-D.

```
tnm$
```

Typing `foo` shows nothing on the command line. Press enter.

```
tnm$  -bash: foo: command not found
```

Press enter several times again. Prompts continue to be displayed on a single line.

```
tnm$  tnm$ tnm$  tnm$
```

Commands do work (after one hits enter), but whatever is typed is not displayed, and in general the terminal is not usable.

**Comment by slandelle** [comment]
Closing as I don't think this will ever be investigated; IMHO, `scala:console` should be dropped in a future major version.
