### ISSUE TITLE
scala-maven-plugin version for scala-library 2.12.15?

### ISSUE THREAD

**Issue by raisinbl** [davidB/scala-maven-plugin#737]
I need to run Spark on my project which having both scala and java code. I just found that the `scala-maven-plugin` is suitable for doing that thing, in my project, the Spark version **3.x** is only using scala 2.12 version or 2.13, whereas the major scala version is _2.12.15_. I found that none of `scala-maven-plugin` version is compatible, when I `mvn compile` it's always raise build/compile failed exception. Here's my full [log](https://gist.githubusercontent.com/raisinbl/e1050c01138b6413f136938d5312a8a0/raw/97503695eb39e8b14d804950db2956d2ea00ef97/log-maven-scala) and [`pom.xml`](https://gist.github.com/raisinbl/e1050c01138b6413f136938d5312a8a0/raw/97503695eb39e8b14d804950db2956d2ea00ef97/pom.xml)
I notice only to scala **2.12.18** and scala-maven-plugin **4.8.1** can compile, but as I expect, spark can't use because maybe compatible problem between scala and java version :)

p/s: any tips when choosing `scala` and `scala-maven-plugin` to make them worked? Thank you for taking your time.

**Comment by slandelle** [comment]
> whereas the major scala version is 2.12.15

No, 2.12.15 is not a major version. It's a minor version.

2 is the generation
12 is the major version
15 is the minor version

Hence the `_2.12` suffixes in the artifact names.

Please provide a reproducer matching [these criteria](https://stackoverflow.com/help/minimal-reproducible-example) as a standalone repository on GitHub.

> but as I expect, spark can't use because maybe compatible problem between scala and java version :)

That doesn't make sense. As I said, 2.12.15 and 2.12.18 are minor versions and should be binary compatible. And I fail to see how this would be related to the Java version.

**Comment by raisinbl** [comment]
> > whereas the major scala version is 2.12.15
> 
> No, 2.12.15 is not a major version. It's a minor version.
> 
> 2 is the generation 12 is the major version 15 is the minor version
> 
> Hence the `_2.12` suffixes in the artifact names.

sorry for confusion. what I mean major is majority version of `scala-library` which is a dependency of Spark 3.x, which also needed for the plugin.

> but as I expect, spark can't use because maybe compatible problem between scala and java version :)

for this, maybe I need more time to think about it.
