### ISSUE TITLE
Trouble with installing the Maven plugin in IntelliJ

### ISSUE THREAD

**Issue by rbystrom** [davidB/scala-maven-plugin#750]
Hi. 

I can't figure out how to install Maven in IntelliJ, get the following error:
```
[ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:4.4.0:compile (default) on project "appname": Execution
default of goal net.alchim31.maven:scala-maven-plugin:4.4.0:compile failed: An API incompatibility was encountered while executing 
net.alchim31.maven:scala-maven-plugin:4.4.0:compile: java.lang.NoSuchMethodError: org.fusesource.jansi.AnsiConsole.wrapOutputStream
(Ljava/io/OutputStream;)Ljava/io/OutputStream;
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>net.alchim31.maven:scala-maven-plugin:4.4.0
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
```

I currently have Java 8, as well as Maven 3.9.6 and run on Scala 2.11.12. The error occurs when trying `mvn clean install -U`. The build works perfectly if I were to remove the installation of scala-maven-plugin, so that is the only issue here. Is there some type of compatibility issue, what I need to downgrade anything?
Br,
Richard

**Comment by slandelle** [comment]
Hi,

The latest version of this plugin is 4.8.1.
Please first upgrade prior to asking for help.

Then, if you still experience an issue after upgrading, please provide a way to reproduce your issue, see https://stackoverflow.com/help/minimal-reproducible-example

**Comment by He-Pin** [comment]
@rbystrom The latest version is 4.9.0 now, I'm using it with IDEA too, it works.

**Comment by slandelle** [comment]
The latest version as of now is 4.9.1.
I’m closing this ticket as we have never heard back from the user.
