### ISSUE TITLE
Unable to download 4.9.1 through the Maven repository

### ISSUE THREAD

**Issue by LuciferYang** [davidB/scala-maven-plugin#758]
https://central.sonatype.com/artifact/net.alchim31.maven/scala-maven-plugin/4.8.1/versions

![image](https://github.com/davidB/scala-maven-plugin/assets/1475305/a0b5b8f5-310f-45a5-9fef-ac8b2193b785)

The latest version is still 4.8.1

**Comment by He-Pin** [comment]
@LuciferYang I see only 4.9.0

**Comment by slandelle** [comment]
@davidB tried to create 4.9.0 and then 4.9.1 but they never made it to maven central.
I deleted the unreleased tags and managed to release 4.9.0.

**Comment by LuciferYang** [comment]
Thanks all ~

**Comment by He-Pin** [comment]
I just try with 4.9.1 ,same , thanks.
