### ISSUE TITLE
Release a new version with new zinc?

### ISSUE THREAD

**Issue by He-Pin** [davidB/scala-maven-plugin#778]
Hi thanks for maintaining this plugin, Is there possible to release a new version with the new zinc release, thanks.

**Comment by slandelle** [comment]
Hi,

See https://github.com/davidB/scala-maven-plugin/pull/775#issuecomment-2102150247

**Comment by He-Pin** [comment]
@slandelle  thank you, I found the 4.9.0 will cause class file already defined error when compile (mixed java/scala, bidirectional referenced), I will try 4.9.1.
