### ISSUE TITLE
Failed to execute goal net.alchim31.maven:scala-maven-plugin:4.8.0

### ISSUE THREAD

**Issue by indreshverma** [davidB/scala-maven-plugin#792]
version used...
spark 3.5.1
java 17
scala 2.13.8, 2.13.11, 2.13.13 (these version i have tried with)
scala-maven-plugin 4.8.0, 4.8.1, 4.7.2, 4.9.0(i have tried)

[INFO] Reactor Summary for Spark Project Parent POM 3.5.1:
[INFO] 
[INFO] Spark Project Parent POM ........................... SUCCESS [  6.704 s]
[INFO] Spark Project Tags ................................. SUCCESS [ 10.458 s]
[INFO] Spark Project Sketch ............................... SUCCESS [ 17.464 s]
[INFO] Spark Project Local DB ............................. SUCCESS [ 17.619 s]
[INFO] Spark Project Common Utils ......................... SUCCESS [ 17.107 s]
[INFO] Spark Project Networking ........................... SUCCESS [01:08 min]
[INFO] Spark Project Shuffle Streaming Service ............ SUCCESS [ 22.817 s]
[INFO] Spark Project Unsafe ............................... SUCCESS [ 17.049 s]
[INFO] Spark Project Launcher ............................. SUCCESS [ 14.274 s]
[INFO] Spark Project Core ................................. FAILURE [ 24.362 s]
[INFO] Spark Project ML Local Library ..................... SKIPPED
[INFO] Spark Project GraphX ............................... SKIPPED
[INFO] Spark Project Streaming ............................ SKIPPED
[INFO] Spark Project SQL API .............................. SKIPPED
[INFO] Spark Project Catalyst ............................. SKIPPED
[INFO] Spark Project SQL .................................. SKIPPED
[INFO] Spark Project ML Library ........................... SKIPPED
[INFO] Spark Project Tools ................................ SKIPPED
[INFO] Spark Project Hive ................................. SKIPPED
[INFO] Spark Project REPL ................................. SKIPPED
[INFO] Spark Project Assembly ............................. SKIPPED
[INFO] Kafka 0.10+ Token Provider for Streaming ........... SKIPPED
[INFO] Spark Integration for Kafka 0.10 ................... SKIPPED
[INFO] Kafka 0.10+ Source for Structured Streaming ........ SKIPPED
[INFO] Spark Project Examples ............................. SKIPPED
[INFO] Spark Integration for Kafka 0.10 Assembly .......... SKIPPED
[INFO] Spark Avro ......................................... SKIPPED
[INFO] Spark Project Connect Common ....................... SKIPPED
[INFO] Spark Protobuf ..................................... SKIPPED
[INFO] Spark Project Connect Server ....................... SKIPPED
[INFO] Spark Project Connect Client ....................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  03:37 min
[INFO] Finished at: 2024-06-26T14:40:55+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:4.8.0:compile (scala-compile-first) on project spark-core_2.13: Execution scala-compile-first of goal net.alchim31.maven:scala-maven-plugin:4.8.0:compile failed: org.apache.commons.exec.ExecuteException.

Pls help.!!

**Comment by slandelle** [comment]
Please reach out to the Spark project.
